"""Scaffold-owned read-side selectors for resource-slot booking.

This package is intended to be generated by the booking scaffold. It keeps
engine reads and booking-state queries out of Django views while leaving the
project provider replaceable.
"""

from .engine import BookingRuntimeEngineGateway, get_booking_engine_gateway

__all__ = ["BookingRuntimeEngineGateway", "get_booking_engine_gateway"]
