# Generated by Django 5.2.11 on 2026-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="topic",
            field=models.CharField(
                choices=[
                    ("general", "General Question"),
                    ("booking", "Questions about Booking"),
                    ("job", "Job / Career"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=50,
                verbose_name="Topic",
            ),
        ),
    ]
