# Generated by Django 5.2.11 on 2026-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_service_excludes"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="parallel_ok",
            field=models.BooleanField(
                default=True,
                help_text="Whether this service can be performed simultaneously with other services in a chain booking (by different masters). True = manicure + pedicure at the same time is OK. False = must be strictly sequential.",
                verbose_name="Can Run in Parallel",
            ),
        ),
    ]
