# Generated by Django 5.2.11 on 2026-02-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="StaticPageSeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_de",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("contacts", "Contacts Page"),
                            ("team", "Team Page"),
                            ("services_index", "Services List Page"),
                            ("impressum", "Impressum"),
                            ("datenschutz", "Datenschutz"),
                        ],
                        help_text="Unique identifier for the static page.",
                        max_length=50,
                        unique=True,
                        verbose_name="Page Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page SEO",
                "verbose_name_plural": "Static Pages SEO",
            },
        ),
    ]
