# Generated by Django 5.2.11 on 2026-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_load_seo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="LILY Beauty Salon",
                        max_length=255,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        default="Liliia Yakina",
                        max_length=255,
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tax Number (Steuernummer)",
                    ),
                ),
                (
                    "phone",
                    models.CharField(default="+49 176 59423704", max_length=50, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@lily-salon.de",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address_street",
                    models.CharField(
                        default="Lohmannstraße 111",
                        max_length=255,
                        verbose_name="Street",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        default="06366 Köthen (Anhalt)",
                        max_length=255,
                        verbose_name="City & ZIP",
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to open location in Maps",
                        verbose_name="Google Maps Link",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True,
                        default="https://instagram.com/manikure_kothen",
                        verbose_name="Instagram URL",
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Telegram URL"),
                ),
                (
                    "whatsapp_url",
                    models.URLField(blank=True, verbose_name="WhatsApp URL"),
                ),
                (
                    "working_hours_weekdays",
                    models.CharField(default="09:00 - 18:00", max_length=100, verbose_name="Mo-Fr"),
                ),
                (
                    "working_hours_saturday",
                    models.CharField(default="10:00 - 14:00", max_length=100, verbose_name="Saturday"),
                ),
                (
                    "working_hours_sunday",
                    models.CharField(default="Geschlossen", max_length=100, verbose_name="Sunday"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
