# Generated by Django 5.2.11 on 2026-02-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_sitesettings_logo_url_sitesettings_url_path_cancel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_base_url",
            field=models.URLField(
                blank=True, help_text="If empty, uses value from .env (SITE_BASE_URL)", verbose_name="Site Base URL"
            ),
        ),
    ]
