# Generated by Django 5.2.11 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_alter_sitesettings_site_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                help_text="GA4 Measurement ID (e.g., G-XXXXXXXXXX)",
                max_length=50,
                verbose_name="Google Analytics ID",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_tag_manager_id",
            field=models.CharField(
                blank=True,
                help_text="GTM Container ID (e.g., GTM-XXXXXXX)",
                max_length=50,
                verbose_name="Google Tag Manager ID",
            ),
        ),
    ]
