# Generated by Django 5.2.11 on 2026-02-11 16:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_sitesettings_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="work_end_saturday",
            field=models.TimeField(default=datetime.time(14, 0), verbose_name="Saturday End"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="work_end_weekdays",
            field=models.TimeField(default=datetime.time(18, 0), verbose_name="Mo-Fr End"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="work_start_saturday",
            field=models.TimeField(default=datetime.time(10, 0), verbose_name="Saturday Start"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="work_start_weekdays",
            field=models.TimeField(default=datetime.time(9, 0), verbose_name="Mo-Fr Start"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday",
            field=models.CharField(default="10:00 - 14:00", max_length=100, verbose_name="Saturday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_de",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_en",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_ru",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_uk",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday",
            field=models.CharField(default="Geschlossen", max_length=100, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_de",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_en",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_ru",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_uk",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays",
            field=models.CharField(default="09:00 - 18:00", max_length=100, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_de",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_en",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_ru",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_uk",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
    ]
