# Generated by Django 5.2.11 on 2026-02-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_sitesettings_google_analytics_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_bot_username",
            field=models.CharField(
                blank=True,
                help_text="Username of the bot without @ (e.g., lily_beauty_bot)",
                max_length=100,
                verbose_name="Telegram Bot Username",
            ),
        ),
    ]
