# Generated by Django 5.2.11 on 2026-02-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_sitesettings_telegram_bot_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="telegram_bot_username",
            field=models.CharField(
                blank=True,
                default="codexen_test_bot",
                help_text="Username of the bot without @ (e.g., lily_beauty_bot)",
                max_length=100,
                verbose_name="Telegram Bot Username",
            ),
        ),
    ]
