# Generated by Django 5.2.11 on 2026-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_sitesettings_telegram_bot_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook URL"),
        ),
    ]
