# Generated by Django 5.2.11 on 2026-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_sitesettings_facebook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_url",
            field=models.CharField(
                blank=True,
                default="/static/img/logo_lily.webp",
                help_text="Can be an absolute URL or a relative static path.",
                max_length=500,
                verbose_name="Logo URL",
            ),
        ),
    ]
