# Generated by Django 5.2.11 on 2026-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_statictranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="url_path_reschedule",
            field=models.CharField(
                default="/cabinet/appointments/reschedule/{token}/",
                max_length=255,
                verbose_name="Booking Reschedule URL Path",
            ),
        ),
    ]
