# Generated by Django 5.2.11 on 2026-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_alter_sitesettings_url_path_reschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'ct_receipt_body')",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General / Shared"),
                            ("booking", "Booking System"),
                            ("contacts", "Contact Form / CRM"),
                            ("marketing", "Marketing / Newsletters"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The actual text to be sent in emails. Supports placeholders like {{ client_name }}.",
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_de",
                    models.TextField(
                        help_text="The actual text to be sent in emails. Supports placeholders like {{ client_name }}.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        help_text="The actual text to be sent in emails. Supports placeholders like {{ client_name }}.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_uk",
                    models.TextField(
                        help_text="The actual text to be sent in emails. Supports placeholders like {{ client_name }}.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        help_text="The actual text to be sent in emails. Supports placeholders like {{ client_name }}.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Internal note for admin.", max_length=255, verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Content Block",
                "verbose_name_plural": "Email Content Blocks",
                "ordering": ["category", "key"],
            },
        ),
    ]
