# Generated by Django 5.2.12 on 2026-04-08 00:06

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(db_index=True, max_length=500, verbose_name="path")),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="views")),
            ],
        ),
    ]
