# Generated by Django 5.2.13 on 2026-04-09 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageview",
            options={"ordering": ["-date", "-views"], "verbose_name": "Page view", "verbose_name_plural": "Page views"},
        ),
        migrations.AlterUniqueTogether(
            name="pageview",
            unique_together={("path", "date")},
        ),
    ]
