# Generated by Django 5.2.13 on 2026-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations: list[migrations.operations.base.Operation] = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=100, verbose_name="event type")),
                ("channel", models.CharField(max_length=20, verbose_name="channel")),
                ("recipient", models.CharField(max_length=255, verbose_name="recipient")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")], max_length=20, verbose_name="status"
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, verbose_name="subject")),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("context_preview", models.JSONField(blank=True, default=dict, verbose_name="context preview")),
                ("sent_at", models.DateTimeField(auto_now_add=True, verbose_name="sent at")),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("name", models.CharField(blank=True, max_length=150, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[("admin", "Administrator"), ("manager", "Manager")],
                        default="admin",
                        max_length=20,
                        verbose_name="role/kind",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("note", models.TextField(blank=True, verbose_name="internal note")),
            ],
            options={
                "verbose_name": "Notification Recipient",
                "verbose_name_plural": "Notification Recipients",
                "ordering": ["email"],
            },
        ),
    ]
