# Generated by Django 5.2.13 on 2026-04-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrecipient",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="internal note"),
        ),
    ]
