# Generated by Django 5.2.11 on 2026-02-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_initial"),
        ("promos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="active_promo",
            field=models.ForeignKey(
                blank=True,
                help_text="Promo that was active when booking was made",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="promos.promomessage",
                verbose_name="Active Promo",
            ),
        ),
    ]
