# Generated by Django 5.2.11 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_master_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="finalize_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name="Finalization Token"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="price_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final price entered by administrator",
                max_digits=10,
                null=True,
                verbose_name="Actual Price (€)",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client", "Cancelled by Client"),
                    ("master", "Cancelled by Master"),
                    ("reschedule", "Rescheduled"),
                    ("master_busy", "Master is busy"),
                    ("master_ill", "Master is ill"),
                    ("no_materials", "Missing materials"),
                    ("client_blacklist", "Client in blacklist"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Cancellation Reason",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                    ("reschedule_proposed", "Reschedule Proposed"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
