# Generated by Django 5.2.11 on 2026-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_bookingsettings_master_break_end_master_break_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="max_clients_parallel",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many clients this master can serve simultaneously. 1 = one at a time (default). 2+ = group booking support (e.g. couples pedicure). Used with BookingEngineRequest.group_size.",
                verbose_name="Max Parallel Clients",
            ),
        ),
    ]
