# Generated by Django 5.2.11 on 2026-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_master_add_max_clients_parallel"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="timezone",
            field=models.CharField(
                default="Europe/Berlin",
                help_text="Master's local timezone (e.g. 'Europe/Berlin')",
                max_length=50,
                verbose_name="Timezone",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                    ("reschedule_proposed", "Reschedule Proposed"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
