# Generated by Django 5.2.11 on 2026-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_master_timezone_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="lang",
            field=models.CharField(
                default="de",
                help_text="Language used during booking (for notifications)",
                max_length=5,
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="appointmentgroup",
            name="lang",
            field=models.CharField(
                default="de", help_text="Language used during booking", max_length=10, verbose_name="Language"
            ),
        ),
    ]
