# Generated by Django 5.2.13 on 2026-04-09 09:25

import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0008_userprofile_notify_reminders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group_token",
                    models.CharField(
                        db_index=True,
                        help_text="Used in the success page URL. Auto-generated on save.",
                        max_length=64,
                        unique=True,
                        verbose_name="group token",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("same_day", "Same Day")], default="same_day", max_length=20, verbose_name="mode"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("website", "Website"), ("admin", "Admin Panel")],
                        default="website",
                        max_length=20,
                        verbose_name="booking source",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "Appointment Group",
                "verbose_name_plural": "Appointment Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentGroupItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="order in chain")),
            ],
            options={
                "verbose_name": "Group Item",
                "verbose_name_plural": "Group Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "step_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Time grid granularity for the booking engine.",
                        verbose_name="Slot Step (min)",
                    ),
                ),
                (
                    "default_buffer_between_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Default Buffer Between Appointments (min)"),
                ),
                (
                    "min_advance_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Global minimum; masters can override individually.",
                        verbose_name="Minimum Advance Booking (min)",
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(default=60, verbose_name="Maximum Advance Booking (days)"),
                ),
                ("work_start_weekdays", models.TimeField(blank=True, null=True, verbose_name="Weekday Start")),
                ("work_end_weekdays", models.TimeField(blank=True, null=True, verbose_name="Weekday End")),
                ("work_start_saturday", models.TimeField(blank=True, null=True, verbose_name="Saturday Start")),
                ("work_end_saturday", models.TimeField(blank=True, null=True, verbose_name="Saturday End")),
            ],
            options={
                "verbose_name": "Resource-Slot Booking Settings",
                "verbose_name_plural": "Resource-Slot Booking Settings",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_start", models.TimeField(blank=True, null=True, verbose_name="Work Start")),
                ("work_end", models.TimeField(blank=True, null=True, verbose_name="Work End")),
                ("break_start", models.TimeField(blank=True, null=True, verbose_name="Break Start")),
                ("break_end", models.TimeField(blank=True, null=True, verbose_name="Break End")),
                (
                    "buffer_between_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overrides global default when set.",
                        null=True,
                        verbose_name="Buffer Between Appointments (min)",
                    ),
                ),
                (
                    "min_advance_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How far in advance a client must book.",
                        null=True,
                        verbose_name="Minimum Advance Booking (min)",
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How far ahead a client can book.",
                        null=True,
                        verbose_name="Maximum Advance Booking (days)",
                    ),
                ),
                (
                    "max_clients_parallel",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Max Parallel Clients"),
                ),
                ("timezone", models.CharField(blank=True, default="UTC", max_length=64, verbose_name="Timezone")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Leiterin & Inhaberin'",
                        max_length=255,
                        verbose_name="professional title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Leiterin & Inhaberin'",
                        max_length=255,
                        null=True,
                        verbose_name="professional title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Leiterin & Inhaberin'",
                        max_length=255,
                        null=True,
                        verbose_name="professional title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Leiterin & Inhaberin'",
                        max_length=255,
                        null=True,
                        verbose_name="professional title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Leiterin & Inhaberin'",
                        max_length=255,
                        null=True,
                        verbose_name="professional title",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="masters/", verbose_name="photo")),
                ("bio", models.TextField(blank=True, verbose_name="biography")),
                ("bio_de", models.TextField(blank=True, null=True, verbose_name="biography")),
                ("bio_en", models.TextField(blank=True, null=True, verbose_name="biography")),
                ("bio_ru", models.TextField(blank=True, null=True, verbose_name="biography")),
                ("bio_uk", models.TextField(blank=True, null=True, verbose_name="biography")),
                ("short_description", models.CharField(blank=True, max_length=500, verbose_name="short description")),
                (
                    "short_description_de",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="short description"),
                ),
                (
                    "short_description_en",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="short description"),
                ),
                (
                    "short_description_ru",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="short description"),
                ),
                (
                    "short_description_uk",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="short description"),
                ),
                ("years_experience", models.PositiveIntegerField(default=0, verbose_name="years of experience")),
                ("instagram", models.CharField(blank=True, max_length=100, verbose_name="instagram handle")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="direct phone")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("vacation", "On Vacation"),
                            ("training", "In Training"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("is_owner", models.BooleanField(default=False, verbose_name="is owner")),
                ("is_featured", models.BooleanField(default=False, verbose_name="featured")),
                ("is_public", models.BooleanField(db_index=True, default=True, verbose_name="visible on site")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="display order")),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, unique=True, verbose_name="telegram ID"
                    ),
                ),
                ("telegram_username", models.CharField(blank=True, max_length=100, verbose_name="telegram username")),
                (
                    "bot_access_code",
                    models.CharField(
                        blank=True,
                        help_text="One-time code for Telegram bot registration",
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="bot access code",
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name="QR token"),
                ),
            ],
            options={
                "verbose_name": "Master",
                "verbose_name_plural": "Masters",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MasterDayOff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True, verbose_name="Date")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Reason")),
            ],
            options={
                "verbose_name": "Day Off",
                "verbose_name_plural": "Days Off",
            },
        ),
        migrations.CreateModel(
            name="MasterWorkingDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                ("break_start", models.TimeField(blank=True, null=True, verbose_name="Break Start")),
                ("break_end", models.TimeField(blank=True, null=True, verbose_name="Break End")),
            ],
            options={
                "verbose_name": "Working Day",
                "verbose_name_plural": "Working Days",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("reschedule_proposed", "Reschedule Proposed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("datetime_start", models.DateTimeField(db_index=True, verbose_name="Start Time")),
                ("duration_minutes", models.PositiveIntegerField(verbose_name="Duration (min)")),
                ("lang", models.CharField(default="de", max_length=5, verbose_name="language")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="price (€)")),
                (
                    "price_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="actual price (€)"
                    ),
                ),
                (
                    "finalize_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="finalization token",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("telegram", "Telegram Bot"),
                            ("phone", "Phone"),
                            ("admin", "Admin Panel"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="booking source",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="cancelled at")),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Cancelled by Client"),
                            ("master", "Cancelled by Master"),
                            ("reschedule", "Rescheduled"),
                            ("master_busy", "Master is busy"),
                            ("master_ill", "Master is ill"),
                            ("no_materials", "Missing materials"),
                            ("client_blacklist", "Client in blacklist"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="cancellation reason",
                    ),
                ),
                ("cancel_note", models.TextField(blank=True, verbose_name="cancellation note")),
                ("client_notes", models.TextField(blank=True, verbose_name="client notes")),
                ("admin_notes", models.TextField(blank=True, verbose_name="admin notes")),
                ("reminder_sent", models.BooleanField(default=False, verbose_name="reminder sent")),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="reminder sent at")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="system.client",
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-datetime_start"],
            },
        ),
    ]
