# Generated by Django 5.2.13 on 2026-04-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("main", "0001_initial"),
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="main.service",
                verbose_name="service",
            ),
        ),
        migrations.AddField(
            model_name="appointmentgroup",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_groups",
                to="system.client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="appointmentgroup",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_groups",
                to="main.servicecombo",
                verbose_name="applied combo/promo",
            ),
        ),
        migrations.AddField(
            model_name="appointmentgroupitem",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_item",
                to="booking.appointment",
                verbose_name="appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentgroupitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="booking.appointmentgroup",
                verbose_name="group",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="masters", to="main.servicecategory", verbose_name="categories"
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="booking.master",
                verbose_name="master",
            ),
        ),
        migrations.AddField(
            model_name="masterdayoff",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days_off",
                to="booking.master",
                verbose_name="master",
            ),
        ),
        migrations.AddField(
            model_name="masterworkingday",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_days",
                to="booking.master",
                verbose_name="master",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentgroup",
            index=models.Index(fields=["status", "created_at"], name="booking_app_status_e4639c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentgroupitem",
            unique_together={("group", "order")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["master", "datetime_start"], name="booking_app_master__f409ed_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status", "datetime_start"], name="booking_app_status_b4a9a1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="masterdayoff",
            unique_together={("master", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="masterworkingday",
            unique_together={("master", "weekday")},
        ),
    ]
