# Generated by Django 5.2.13 on 2026-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_description_de",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_description_en",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_image",
            field=models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_title_de",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_title_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_title_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="master",
            name="seo_title_uk",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
    ]
