# Generated by Django 5.2.13 on 2026-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_master_seo_description_master_seo_description_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsettings",
            name="book_only_from_next_day",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, users can only book slots starting from tomorrow.",
                verbose_name="Book only from next day",
            ),
        ),
        migrations.AddField(
            model_name="bookingsettings",
            name="sync_with_site_settings",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, work hours will be synchronized from global Site Settings.",
                verbose_name="Sync with Site Settings",
            ),
        ),
    ]
