# Generated by Django 5.2.13 on 2026-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_bookingsettings_book_only_from_next_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsettings",
            name="load_strategy",
            field=models.CharField(
                choices=[("fill_first", "Fill first (by priority)"), ("even_load", "Even load (balance bookings)")],
                default="fill_first",
                help_text="fill_first: assign bookings to masters with lower booking_priority first. even_load: assign to the master with fewest bookings on the target date.",
                max_length=20,
                verbose_name="master load strategy",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="booking_priority",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=100,
                help_text="Lower value = booked first. Controls which master receives new bookings first (fill_first strategy).",
                verbose_name="booking priority",
            ),
        ),
    ]
