"""Scaffold-owned service layer for resource-slot booking.

This package is intended to be generated by the booking scaffold. It contains
feature workflows and cabinet-state assembly while leaving project providers
and mappings replaceable.
"""
