"""Scaffold-owned cabinet workflows for resource-slot booking.

This file is intended to be generated by the booking scaffold. It adapts the
project provider into cabinet-facing state contracts while keeping cabinet UI
generic and data-driven.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import replace
from datetime import datetime, time, timedelta
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from collections.abc import Mapping

from codex_django.booking import (
    BookingActionResult,
    BookingBridge,
    BookingFormFieldState,
    BookingFormState,
    BookingModalActionState,
    BookingModalState,
    BookingProfileState,
    BookingQuickCreateState,
    BookingSlotOptionState,
    BookingSlotPickerState,
    BookingSummaryItemState,
)
from codex_django.booking.cabinet.types import (
    BookingSummaryData,
    ClientSelectorData,
    DateTimePickerData,
    ServiceItem,
    ServiceSelectorData,
)
from codex_django.cabinet import CalendarGridData, CalendarSlot
from django.core.paginator import Paginator
from django.urls import reverse

from ..providers import get_booking_project_data_provider
from .cabinet_availability import CabinetBookingAvailabilityService


class BookingCabinetWorkflowService:
    """Default cabinet workflow over the active booking project provider."""

    BLOCKING_SCHEDULE_STATUSES = {"pending", "confirmed", "reschedule_proposed"}
    LIST_PAGE_SIZE = 15

    def __init__(self, provider: Any = None) -> None:
        self.provider = provider or get_booking_project_data_provider()
        from ..booking_settings import BookingSettings

        self.settings = BookingSettings.load()
        self.builder_day_horizon = self.settings.max_advance_days
        self.availability = CabinetBookingAvailabilityService()

    @staticmethod
    def modal_url(booking_id: int, *, mode: str | None = None) -> str:
        url = reverse("cabinet:booking_modal", kwargs={"pk": booking_id})
        return f"{url}?mode={mode}" if mode else url

    @staticmethod
    def _get_client_color(name: str) -> str:
        import hashlib

        h = int(hashlib.sha256(name.encode()).hexdigest(), 16)
        hue = (h % 36) * 10
        return f"hsla({hue}, 75%, 45%, 0.3)"

    @staticmethod
    def _get_client_border(name: str) -> str:
        import hashlib

        h = int(hashlib.sha256(name.encode()).hexdigest(), 16)
        hue = (h % 36) * 10
        return f"hsl({hue}, 80%, 35%)"

    def get_schedule_context(self, request: Any) -> dict[str, Any]:
        today = datetime.today().strftime("%Y-%m-%d")
        current_date = request.GET.get("date", today)
        if current_date == "today":
            current_date = today
        current_dt = datetime.strptime(current_date, "%Y-%m-%d")
        day_schedule = self.settings.get_day_schedule(current_dt.weekday())
        if day_schedule is None:
            first_open = next(
                (
                    self.settings.get_day_schedule(idx)
                    for idx in range(7)
                    if self.settings.get_day_schedule(idx) is not None
                ),
                None,
            )
            day_schedule = first_open or (time(9, 0), time(18, 0))
        day_start = day_schedule[0].hour
        day_end = day_schedule[1].hour
        step = self.settings.step_minutes or 30
        rows_data = []
        for hour in range(day_start, day_end):
            for minute in range(0, 60, step):
                rows_data.append({"hour": str(hour), "min": f"{minute:02d}"})

        masters = self.provider.get_cabinet_masters()
        cols: list[dict[str, Any]] = []
        for master in masters:
            initials = "".join(part[0] for part in master["name"].split())[:2].upper()
            cols.append(
                {
                    "name": master["name"],
                    "avatar": initials,
                    "info": "4 appts.",
                    "color": "#6366f1" if "Lily" in master["name"] else "#10b981",
                }
            )

        master_id_to_idx = {master["id"]: index for index, master in enumerate(masters)}
        events = []
        show_cancelled = request.GET.get("show_cancelled") == "1"
        for appt in self.provider.get_cabinet_appointments():
            if str(appt.get("date")) != current_date:
                continue
            status = str(appt.get("status", "pending"))
            if status not in self.BLOCKING_SCHEDULE_STATUSES and not (show_cancelled and status == "cancelled"):
                continue
            master_id = appt["master_id"]
            if master_id not in master_id_to_idx:
                continue
            try:
                start_dt = datetime.strptime(str(appt["time"]), "%H:%M").time()
            except ValueError:
                start_dt = time(10, 0)
            col_idx = master_id_to_idx[master_id]
            rows_per_hour = 60 // step
            row_idx = (start_dt.hour - day_start) * rows_per_hour + (start_dt.minute // step)
            duration = int(appt.get("duration", 60))
            span = max(1, duration // step)
            client_name = str(appt.get("client_name", "Unknown"))
            service_title = str(appt.get("service_title", "Service"))
            price = int(appt.get("price", 0))
            appt_id = int(appt.get("id", 0))
            details = []
            indicators = []
            note = appt.get("admin_notes", "") or appt.get("client_notes", "")

            # Logical "New Client" badge (e.g. registered in the last 7 days)
            client_created_at = appt.get("client_created_at")
            if client_created_at:
                try:
                    created_dt = datetime.fromisoformat(client_created_at)
                    # We use .date() comparison to avoid timezone issues for "newness"
                    if (datetime.now().date() - created_dt.date()).days < 7:
                        details.append({"text": "New Client", "style": "info"})
                        indicators.append("bi-person-plus")
                except (ValueError, TypeError):
                    pass
            if duration > 60:
                indicators.append("bi-clock-history")
            events.append(
                CalendarSlot(
                    col=col_idx,
                    row=row_idx,
                    span=span,
                    title=client_name,
                    subtitle=service_title,
                    color=self._get_client_color(client_name),
                    left_border=self._get_client_border(client_name),
                    badge=status.upper(),
                    badge_style="dashed" if status == "pending" else "solid",
                    price=f"${price}",
                    url=self.modal_url(appt_id),
                    details=details,
                    note=note,
                    indicators=indicators,
                )
            )

        calendar = CalendarGridData(
            cols=cast("list[Any]", cols),
            rows=[f"{row['hour']}:{row['min']}" for row in rows_data],
            events=events,
            title=current_date,
            current_date=datetime.strptime(current_date, "%Y-%m-%d"),
            new_event_url=f"{reverse('cabinet:booking_modal', kwargs={'pk': 0})}?mode=create_from_slot&date={current_date}",
            prev_url=f"?date={(datetime.strptime(current_date, '%Y-%m-%d') - timedelta(days=1)).strftime('%Y-%m-%d')}",
            next_url=f"?date={(datetime.strptime(current_date, '%Y-%m-%d') + timedelta(days=1)).strftime('%Y-%m-%d')}",
            today_url="?date=today",
            slot_height="44px",
            time_col_width="60px",
            col_width="minmax(220px, 300px)",
        )
        return {"calendar": calendar, "rows": rows_data}

    @staticmethod
    def _category_key(category: Any) -> str:
        return str(getattr(category, "bento_group", "") or getattr(category, "slug", ""))

    def _get_selector_categories(self, services: list[dict[str, Any]]) -> list[tuple[str, str]]:
        service_categories = {str(service.get("category", "all")) for service in services}
        return [
            (self._category_key(cat), cat.name)
            for cat in self.provider.get_service_categories()
            if self._category_key(cat) in service_categories
        ]

    def _get_booking_builder_tabs(self, *, mode: str) -> list[dict[str, str]]:
        return [
            {
                "key": "single",
                "label": "Single session",
                "url": f"{reverse('cabinet:booking_new')}?mode=single",
                "active": "true" if mode == "single" else "",
            },
            {
                "key": "separate",
                "label": "Separate booking",
                "url": f"{reverse('cabinet:booking_new')}?mode=separate",
                "active": "true" if mode == "separate" else "",
            },
            {
                "key": "series",
                "label": "Series plan",
                "url": f"{reverse('cabinet:booking_new')}?mode=series",
                "active": "true" if mode == "series" else "",
            },
        ]

    def _build_separate_booking_context(self, *, mode: str) -> dict[str, Any]:
        services = self.provider.get_cabinet_services()
        masters = self.provider.get_cabinet_masters()
        start_date = datetime.today().date()
        available_days = self.availability.build_picker_days(start_date=start_date, horizon=self.builder_day_horizon)

        categories = self._get_selector_categories(services)
        selector = ServiceSelectorData(
            items=[
                ServiceItem(
                    id=str(service["id"]),
                    title=service["title"],
                    price=str(service["price"]),
                    duration=service["duration"],
                    category=service.get("category", "all"),
                    master_ids=list(service.get("master_ids", [])),
                    exclusive_group=str(service.get("exclusive_group", "")),
                    conflicts_with=[str(item) for item in service.get("conflicts_with", [])],
                    replacement_mode=str(service.get("replacement_mode", "replace")),
                )
                for service in services
            ],
            categories=categories,
        )
        picker = DateTimePickerData(
            available_days=available_days,
            time_slots=[],
            busy_slots=[],
            current_month=cast("str", available_days[0]["month_label"] if available_days else ""),
            default_date="",
            slot_matrix_json="{}",
        )
        return {
            "title": "Separate booking",
            "builder_mode": mode,
            "builder_tabs": self._get_booking_builder_tabs(mode=mode),
            "selector": selector,
            "picker": picker,
            "client_selector": ClientSelectorData(clients=self.provider.get_cabinet_clients()),
            "separate_services": [
                {
                    "id": str(service["id"]),
                    "title": service["title"],
                    "duration": service["duration"],
                    "price": service["price"],
                }
                for service in services
            ],
            "separate_masters": [{"id": master["id"], "name": master["name"]} for master in masters],
            "separate_confirm_url": reverse("cabinet:booking_create"),
        }

    def _build_series_booking_context(self, *, mode: str) -> dict[str, Any]:
        services = self.provider.get_cabinet_services()
        clients = self.provider.get_cabinet_clients()
        masters = self.provider.get_cabinet_masters()
        start_date = datetime.today().date()
        available_days = self.availability.build_picker_days(start_date=start_date, horizon=self.builder_day_horizon)
        return {
            "title": "Series booking",
            "builder_mode": mode,
            "builder_tabs": self._get_booking_builder_tabs(mode=mode),
            "series_defaults": {
                "course_length": 10,
                "cadence": "every_3_days",
                "min_gap_days": 3,
                "start_date": datetime.today().strftime("%Y-%m-%d"),
                "client_count": len(clients),
            },
            "series_services": [
                {
                    "id": str(service["id"]),
                    "title": service["title"],
                    "duration": service["duration"],
                    "price": service["price"],
                }
                for service in services
            ],
            "series_masters": [{"id": str(master["id"]), "name": master["name"]} for master in masters],
            "series_clients": clients,
            "client_selector": ClientSelectorData(clients=clients),
            "picker": DateTimePickerData(
                available_days=available_days,
                time_slots=[],
                busy_slots=[],
                current_month=cast("str", available_days[0]["month_label"] if available_days else ""),
                default_date="",
                slot_matrix_json="{}",
            ),
        }

    def get_new_booking_context(self, request: Any) -> dict[str, Any]:
        mode = request.GET.get("mode", "single")
        if mode == "separate":
            return self._build_separate_booking_context(mode=mode)
        if mode == "series":
            return self._build_series_booking_context(mode=mode)

        services = self.provider.get_cabinet_services()
        masters = self.provider.get_cabinet_masters()
        start_date = datetime.today().date()
        available_days = self.availability.build_picker_days(start_date=start_date, horizon=self.builder_day_horizon)
        service_items = [
            ServiceItem(
                id=str(service["id"]),
                title=service["title"],
                price=str(service["price"]),
                duration=service["duration"],
                category=service.get("category", "all"),
                master_ids=list(service.get("master_ids", [])),
                exclusive_group=str(service.get("exclusive_group", "")),
                conflicts_with=[str(item) for item in service.get("conflicts_with", [])],
                replacement_mode=str(service.get("replacement_mode", "replace")),
            )
            for service in services
        ]
        categories = self._get_selector_categories(services)
        selector = ServiceSelectorData(
            items=service_items,
            categories=categories,
        )
        picker = DateTimePickerData(
            available_days=available_days,
            time_slots=[],
            busy_slots=[],
            current_month=cast("str", available_days[0]["month_label"] if available_days else ""),
            default_date="",
            slot_matrix_json="{}",
        )
        summary = BookingSummaryData(
            confirm_url=reverse("cabinet:booking_create"),
            masters=[{"id": master["id"], "name": master["name"]} for master in masters],
        )
        return {
            "title": "New booking",
            "builder_mode": mode,
            "builder_tabs": self._get_booking_builder_tabs(mode=mode),
            "selector": selector,
            "picker": picker,
            "summary": summary,
            "client_selector": ClientSelectorData(clients=self.provider.get_cabinet_clients()),
        }

    def create_new_booking(self, request: Any) -> dict[str, Any]:
        try:
            payload = json.loads(request.POST.get("data", "{}"))
        except json.JSONDecodeError:
            return {
                "ok": False,
                "target_url": reverse("cabinet:booking_new"),
                "message": "Invalid booking payload.",
            }

        mode = str(payload.get("mode", "single"))
        selected_date = str(payload.get("date", "")).strip()
        selected_time = str(payload.get("time", "")).strip()
        services = payload.get("services") or []
        client_payload = payload.get("client") or {}
        if not services:
            return {
                "ok": False,
                "target_url": reverse("cabinet:booking_new"),
                "message": "Incomplete booking data.",
            }
        if mode != "separate" and (not selected_date or not selected_time):
            return {
                "ok": False,
                "target_url": reverse("cabinet:booking_new"),
                "message": "Incomplete booking data.",
            }

        client_id = client_payload.get("id")
        client_name = str(client_payload.get("name", "")).strip()
        client_phone = str(client_payload.get("phone", "")).strip()
        client_email = str(client_payload.get("email", "")).strip()
        if client_id and str(client_id).isdigit():
            client = next(
                (item for item in self.provider.get_cabinet_clients() if str(item["id"]) == str(client_id)),
                None,
            )
            if client:
                client_name = str(client.get("name", client_name))
                client_phone = str(client.get("phone", client_phone))
                client_email = str(client.get("email", client_email))
        else:
            parts = client_name.split()
            self.provider.create_quick_client(
                first_name=parts[0] if parts else "",
                last_name=" ".join(parts[1:]) if len(parts) > 1 else "",
                phone=client_phone,
                email=client_email,
            )

        service_lookup = {str(service["id"]): service for service in self.provider.get_cabinet_services()}
        created = []
        if mode == "separate":
            first_selected_date = ""
            for service_item in services:
                service_id = str(service_item.get("id", ""))
                service = service_lookup.get(service_id)
                booking_date = str(service_item.get("date", "")).strip()
                start_time = str(service_item.get("time", "")).strip()
                if not service or not booking_date or not start_time:
                    continue
                if not first_selected_date:
                    first_selected_date = booking_date
                master_id = service_item.get("masterId")
                if not master_id:
                    master_ids = list(service.get("master_ids", []))
                    master_id = master_ids[0] if master_ids else 0
                created.append(
                    self.provider.create_quick_appointment(
                        resource_id=int(master_id),
                        booking_date=booking_date,
                        start_time=start_time,
                        service_id=int(service_id),
                        client_name=client_name,
                        client_phone=client_phone,
                        client_email=client_email,
                    )
                )
            target_date = first_selected_date or datetime.today().strftime("%Y-%m-%d")
        else:
            current_dt = datetime.strptime(f"{selected_date} {selected_time}", "%Y-%m-%d %H:%M")
            for service_item in services:
                service_id = str(service_item.get("id", ""))
                service = service_lookup.get(service_id)
                if not service:
                    continue
                master_id = service_item.get("masterId")
                if not master_id:
                    master_ids = list(service.get("master_ids", []))
                    master_id = master_ids[0] if master_ids else 0
                created.append(
                    self.provider.create_quick_appointment(
                        resource_id=int(master_id),
                        booking_date=selected_date,
                        start_time=current_dt.strftime("%H:%M"),
                        service_id=int(service_id),
                        client_name=client_name,
                        client_phone=client_phone,
                        client_email=client_email,
                    )
                )
                current_dt += timedelta(minutes=int(service.get("duration", 30)))
            target_date = selected_date

        errors = [str(item["error"]) for item in created if isinstance(item, dict) and item.get("error")]
        created = [item for item in created if not (isinstance(item, dict) and item.get("error"))]
        if errors:
            return {
                "ok": False,
                "target_url": reverse("cabinet:booking_new"),
                "message": errors[0],
                "created": created,
            }

        target_url = f"{reverse('cabinet:booking_schedule')}?date={target_date}"
        return {
            "ok": bool(created),
            "target_url": target_url,
            "message": f"Created {len(created)} booking item(s)." if created else "Nothing was created.",
            "created": created,
        }

    def get_list_context(self, request: Any, *, status: str | None = None) -> dict[str, Any]:
        request_status = request.GET.get("status")
        if not isinstance(request_status, str):
            request_status = None
        active_status = status or request_status or "all"
        filters = {
            "status": None,
            "master_id": request.GET.get("master_id"),
            "search": request.GET.get("search"),
            "date_from": request.GET.get("date_from"),
            "date_to": request.GET.get("date_to"),
        }
        all_appts = self.provider.get_cabinet_appointments(**filters)
        masters_list = self.provider.get_cabinet_masters()
        masters = {master["id"]: master for master in masters_list}
        appointments = all_appts
        if active_status and active_status != "all":
            appointments = [appt for appt in all_appts if appt["status"] == active_status]
        page_number = request.GET.get("page") or 1
        paginator = Paginator(appointments, self.LIST_PAGE_SIZE)
        page_obj = paginator.get_page(page_number)
        processed_rows = []
        status_map = {
            "pending": {"label": "Pending", "color": "#d97706", "bg": "#fef3c7"},
            "confirmed": {"label": "Confirmed", "color": "#059669", "bg": "#d1fae5"},
            "completed": {"label": "Completed", "color": "#2563eb", "bg": "#dbeafe"},
            "cancelled": {"label": "Cancelled", "color": "#dc2626", "bg": "#fee2e2"},
            "no_show": {"label": "No show", "color": "#7f1d1d", "bg": "#fee2e2"},
            "reschedule_proposed": {"label": "Reschedule", "color": "#7c3aed", "bg": "#ede9fe"},
        }
        for appt in page_obj.object_list:
            master = masters.get(appt["master_id"], {})
            client_name = appt.get("client_name", "Unknown")
            initials = "".join(part[0] for part in client_name.split() if part)[:2].upper()
            style = status_map.get(appt["status"], status_map["pending"])
            processed_rows.append(
                {
                    **appt,
                    "master_name": master.get("name", "Unknown"),
                    "master_initials": "".join(part[0] for part in master.get("name", "").split() if part)[:2].upper(),
                    "initials": initials,
                    "status_label": style["label"],
                    "status_color": style["color"],
                    "status_bg": style["bg"],
                    "client_color": self._get_client_color(client_name),
                }
            )

        counts = {
            "all": len(all_appts),
            "pending": len([appt for appt in all_appts if appt["status"] == "pending"]),
            "confirmed": len([appt for appt in all_appts if appt["status"] == "confirmed"]),
            "completed": len([appt for appt in all_appts if appt["status"] == "completed"]),
            "cancelled": len([appt for appt in all_appts if appt["status"] == "cancelled"]),
            "no_show": len([appt for appt in all_appts if appt["status"] == "no_show"]),
        }
        return {
            "appointments": processed_rows,
            "counts": counts,
            "current_status": active_status or "all",
            "masters_list": masters_list,
            "page_obj": page_obj,
            "paginator": paginator,
            "filters": filters,
        }


class BookingCabinetBridgeAdapter(BookingBridge):
    """Feature-owned cabinet bridge over the booking provider."""

    def __init__(self, provider: Any = None) -> None:
        self.provider = provider or get_booking_project_data_provider()

    @staticmethod
    def _modal_url(booking_id: int, *, mode: str | None = None) -> str:
        url = reverse("cabinet:booking_modal", kwargs={"pk": booking_id})
        return f"{url}?mode={mode}" if mode else url

    def _get_appointment(self, booking_id: int) -> dict[str, Any] | None:
        appointments = self.provider.get_cabinet_appointments()
        return next((item for item in appointments if item["id"] == int(booking_id)), None)

    @staticmethod
    def _build_profile(appt: Mapping[str, Any]) -> BookingProfileState:
        client_name = str(appt.get("client_name", "Unknown"))
        initials = "".join(part[0] for part in client_name.split() if part)[:2].upper()
        return BookingProfileState(name=client_name, subtitle=str(appt.get("phone", "")), avatar=initials)

    @staticmethod
    def _build_summary(appt: Mapping[str, Any]) -> list[BookingSummaryItemState]:
        return [
            BookingSummaryItemState("Service", str(appt.get("service_title", ""))),
            BookingSummaryItemState("Status", str(appt.get("status", "")).upper()),
            BookingSummaryItemState("Time", f"{appt.get('date', 'Today')}, {appt.get('time', '')}"),
            BookingSummaryItemState("Price", f"${appt.get('price', 0)}"),
        ]

    @staticmethod
    def _shift_date(value: str, *, days: int) -> str:
        current = datetime.strptime(value, "%Y-%m-%d").date()
        return (current + timedelta(days=days)).isoformat()

    def _build_slot_picker(
        self, *, booking_id: int, selected_date: str, selected_time: str, master_id: int
    ) -> BookingSlotPickerState:
        available_slots = [
            BookingSlotOptionState(value=slot, label=slot, available=True)
            for slot in self.provider.get_quick_create_slot_options(resource_id=master_id, booking_date=selected_date)
        ]
        return BookingSlotPickerState(
            selected_date=selected_date,
            selected_date_label=datetime.strptime(selected_date, "%Y-%m-%d").strftime("%b %d, %Y"),
            selected_time=selected_time,
            prev_url=f"{self._modal_url(booking_id, mode='reschedule')}&date={self._shift_date(selected_date, days=-1)}",
            next_url=f"{self._modal_url(booking_id, mode='reschedule')}&date={self._shift_date(selected_date, days=1)}",
            today_url=f"{self._modal_url(booking_id, mode='reschedule')}&date=today",
            slots=available_slots,
        )

    def _build_quick_create(self, *, request: Any, schedule_date: str, col: int, row: int) -> BookingQuickCreateState:
        prefill = self.provider.get_schedule_prefill(schedule_date=schedule_date, col=col, row=row)
        services = self.provider.get_quick_create_services(
            resource_id=prefill.resource_id,
            booking_date=prefill.booking_date,
            start_time=prefill.start_time,
        )
        clients = self.provider.get_quick_create_clients()
        return BookingQuickCreateState(
            prefill=prefill,
            service_options=services,
            client_options=clients,
            selected_service_id=services[0].value if services else "",
            selected_client_id="",
            allow_new_client=True,
        )

    def get_modal_state(self, request: Any, booking_id: int, mode: str) -> BookingModalState:
        if mode == "create_from_slot":
            schedule_date = request.GET.get("date", datetime.today().strftime("%Y-%m-%d"))
            col = int(request.GET.get("col", 0))
            row = int(request.GET.get("row", 0))
            quick_create = self._build_quick_create(request=request, schedule_date=schedule_date, col=col, row=row)
            return BookingModalState(
                booking_id=0,
                title="Create booking",
                mode=mode,
                summary_items=[
                    BookingSummaryItemState("Master", quick_create.prefill.resource_name),
                    BookingSummaryItemState("Date", quick_create.prefill.booking_date),
                    BookingSummaryItemState("Time", quick_create.prefill.start_time),
                ],
                quick_create=quick_create,
                actions=[
                    BookingModalActionState(
                        label="Create Appointment",
                        kind="execute",
                        value="create_from_slot",
                        method="POST",
                        style="btn-primary",
                        icon="bi-plus-circle",
                    ),
                    BookingModalActionState(label="Close", kind="close", style="btn-secondary"),
                ],
            )

        appt = self._get_appointment(booking_id)
        if not appt:
            return BookingModalState(booking_id=booking_id, title="Not Found", mode=mode)

        state = BookingModalState(
            booking_id=booking_id,
            title=f"Booking #{booking_id}",
            mode=mode,
            profile=self._build_profile(appt),
            summary_items=self._build_summary(appt),
        )
        if mode == "confirm":
            return replace(
                state,
                form=BookingFormState(
                    fields=[
                        BookingFormFieldState(
                            name="reply_msg",
                            label="Message to client (Optional)",
                            field_type="textarea",
                            placeholder="Write a personal note...",
                        )
                    ]
                ),
                actions=[
                    BookingModalActionState(
                        label="Confirm Appointment",
                        kind="execute",
                        value="confirm",
                        method="POST",
                        style="btn-primary",
                        icon="bi-check-circle",
                    ),
                    BookingModalActionState(label="Back", kind="open_mode", value="detail", style="btn-secondary"),
                ],
            )
        if mode == "cancel":
            return replace(
                state,
                form=BookingFormState(
                    fields=[
                        BookingFormFieldState(
                            name="cancel_reason",
                            label="Reason for cancellation",
                            field_type="select",
                            value="out_of_time",
                            options=[
                                ("out_of_time", "No available time"),
                                ("master_ill", "Specialist is ill"),
                                ("client_request", "Client requested"),
                                ("other", "Other reason"),
                            ],
                        ),
                        BookingFormFieldState(
                            name="cancel_note",
                            label="Comment",
                            field_type="textarea",
                            placeholder="Describe the reason...",
                        ),
                    ]
                ),
                actions=[
                    BookingModalActionState(
                        label="Confirm Cancellation",
                        kind="execute",
                        value="cancel",
                        method="POST",
                        style="btn-danger",
                        icon="bi-x-circle",
                    ),
                    BookingModalActionState(label="Back", kind="open_mode", value="detail", style="btn-secondary"),
                ],
            )
        if mode == "reschedule":
            selected_date = request.GET.get("date") or str(appt.get("date", datetime.today().strftime("%Y-%m-%d")))
            return replace(
                state,
                slot_picker=self._build_slot_picker(
                    booking_id=booking_id,
                    selected_date=selected_date,
                    selected_time=str(appt.get("time", "")),
                    master_id=int(appt.get("master_id", 0)),
                ),
                actions=[
                    BookingModalActionState(
                        label="Confirm Reschedule",
                        kind="execute",
                        value="reschedule",
                        method="POST",
                        style="btn-primary",
                        icon="bi-calendar-event",
                    ),
                    BookingModalActionState(label="Back", kind="open_mode", value="detail", style="btn-secondary"),
                ],
            )

        status = str(appt.get("status", ""))
        actions = []
        if status == "pending":
            actions.append(
                BookingModalActionState(
                    label="Confirm",
                    kind="open_mode",
                    value="confirm",
                    style="btn-success",
                    icon="bi-check",
                )
            )
        if status == "confirmed":
            actions.extend(
                [
                    BookingModalActionState(
                        label="Complete",
                        kind="execute",
                        value="complete",
                        method="POST",
                        style="btn-success",
                        icon="bi-check2-circle",
                    ),
                    BookingModalActionState(
                        label="No show",
                        kind="execute",
                        value="no_show",
                        method="POST",
                        style="btn-outline-secondary",
                        icon="bi-person-x",
                    ),
                ]
            )
        if status in {"pending", "confirmed", "reschedule_proposed"}:
            actions.extend(
                [
                    BookingModalActionState(
                        label="Reschedule",
                        kind="open_mode",
                        value="reschedule",
                        style="btn-outline-primary",
                        icon="bi-calendar-event",
                    ),
                    BookingModalActionState(
                        label="Cancel",
                        kind="open_mode",
                        value="cancel",
                        style="btn-outline-danger",
                        icon="bi-trash",
                    ),
                ]
            )
        if not actions:
            actions.append(BookingModalActionState(label="Close", kind="close", style="btn-secondary"))
        return replace(state, actions=actions)

    def execute_action(self, request: Any, booking_id: int, action: str, payload: Any) -> Any:
        if action == "create_from_slot":
            client_id = payload.get("client_id")
            client_name = str(payload.get("client_name", "")).strip()
            client_phone = str(payload.get("client_phone", "")).strip()
            client_email = str(payload.get("client_email", "")).strip()
            client_first_name = str(payload.get("client_first_name", "")).strip()
            client_last_name = str(payload.get("client_last_name", "")).strip()
            if client_id and client_id != "new":
                client = next(
                    (item for item in self.provider.get_cabinet_clients() if str(item["id"]) == str(client_id)),
                    None,
                )
                if client:
                    client_name = str(client["name"])
                    client_phone = str(client.get("phone", ""))
                    client_email = str(client.get("email", ""))
            else:
                if client_first_name or client_last_name:
                    client_name = " ".join(part for part in [client_first_name, client_last_name] if part).strip()
                if not client_name and client_phone:
                    client_name = client_phone
                if not client_name and client_email:
                    client_name = client_email
                if client_name:
                    self.provider.create_quick_client(
                        first_name=client_first_name,
                        last_name=client_last_name,
                        phone=client_phone,
                        email=client_email,
                    )
                else:
                    return self.provider.run_cabinet_action(
                        booking_id=booking_id,
                        action="unsupported",
                        redirect_url=f"{self._modal_url(0, mode='create_from_slot')}&date={payload.get('date', '2026-03-23')}",
                    )

            if not client_name:
                return self.provider.run_cabinet_action(
                    booking_id=booking_id,
                    action="unsupported",
                    redirect_url=f"{self._modal_url(0, mode='create_from_slot')}&date={payload.get('date', '2026-03-23')}",
                )

            created = self.provider.create_quick_appointment(
                resource_id=int(payload.get("resource_id") or 0),
                booking_date=str(payload.get("date")),
                start_time=str(payload.get("time")),
                service_id=int(payload.get("service_id") or 0),
                client_name=client_name,
                client_phone=client_phone,
                client_email=client_email,
            )
            created_dict = cast("dict[str, Any]", created)
            if created_dict.get("error"):
                return BookingActionResult(
                    ok=False,
                    code=str(created_dict.get("code", "booking-create-error")),
                    message=str(created_dict["error"]),
                    ui_effect="none",
                    target_url="",
                )
            return BookingActionResult(
                ok=True,
                code="booking-create",
                message="Created",
                ui_effect="close_modal",
                target_url=self._modal_url(int(created_dict["id"])),
            )

        if action == "reschedule":
            selected_date = str(payload.get("date"))
            selected_time = str(payload.get("time"))
            updated = self.provider.update_quick_appointment(
                booking_id=booking_id,
                booking_date=selected_date,
                start_time=selected_time,
            )
            updated_dict = cast("dict[str, Any] | None", updated)
            if not updated_dict:
                return BookingActionResult(
                    ok=False,
                    code="booking-not-found",
                    message="Appointment not found.",
                    ui_effect="none",
                    target_url="",
                )
            if updated_dict.get("error"):
                return BookingActionResult(
                    ok=False,
                    code=str(updated_dict.get("code", "booking-reschedule-error")),
                    message=str(updated_dict["error"]),
                    ui_effect="none",
                    target_url="",
                )
            return BookingActionResult(
                ok=True,
                code="booking-reschedule",
                message="Rescheduled",
                ui_effect="close_modal",
                target_url=self._modal_url(booking_id),
            )

        del request
        return self.provider.run_cabinet_action(
            booking_id=booking_id,
            action=action,
            redirect_url=self._modal_url(booking_id),
            payload=payload,
        )


_cabinet_workflow = None
_booking_bridge = BookingCabinetBridgeAdapter()


def get_booking_cabinet_workflow() -> BookingCabinetWorkflowService:
    """Return the active cabinet workflow for booking pages."""
    global _cabinet_workflow
    if _cabinet_workflow is None:
        _cabinet_workflow = BookingCabinetWorkflowService()
    return _cabinet_workflow


def get_booking_bridge() -> BookingBridge:
    """Return the feature-owned bridge adapter consumed by cabinet."""

    return _booking_bridge
