"""Scaffold-owned helper utilities for resource-slot booking services.

This file is intended to be generated by the booking scaffold. Keep helpers
small and free of project business logic so projects can override workflows
without touching unrelated parsing helpers.
"""

from __future__ import annotations

from datetime import date, datetime


def parse_iso_date(value: str | None) -> date | None:
    """Parse an ISO date if present; return ``None`` on empty input."""

    if not value:
        return None
    return datetime.strptime(value, "%Y-%m-%d").date()
