# Generated by Django 5.2.11 on 2026-02-16 16:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="PromoMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "title",
                    models.CharField(help_text="Main title of the promotion", max_length=255, verbose_name="Title"),
                ),
                (
                    "title_de",
                    models.CharField(
                        help_text="Main title of the promotion", max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Main title of the promotion", max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Main title of the promotion", max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Main title of the promotion", max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description shown in the modal window", verbose_name="Description"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        help_text="Full description shown in the modal window", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        help_text="Full description shown in the modal window", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        help_text="Full description shown in the modal window", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Full description shown in the modal window", null=True, verbose_name="Description"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Акция!",
                        help_text="Text displayed on the floating button",
                        max_length=100,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_text_de",
                    models.CharField(
                        default="Акция!",
                        help_text="Text displayed on the floating button",
                        max_length=100,
                        null=True,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_text_ru",
                    models.CharField(
                        default="Акция!",
                        help_text="Text displayed on the floating button",
                        max_length=100,
                        null=True,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_text_uk",
                    models.CharField(
                        default="Акция!",
                        help_text="Text displayed on the floating button",
                        max_length=100,
                        null=True,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "button_text_en",
                    models.CharField(
                        default="Акция!",
                        help_text="Text displayed on the floating button",
                        max_length=100,
                        null=True,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, the notification will not be shown even if within the date range",
                        verbose_name="Active",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When to start showing this notification",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(help_text="When to stop showing this notification", verbose_name="End Date"),
                ),
                (
                    "display_delay",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How many seconds to wait after page load before showing the button",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Display Delay (seconds)",
                    ),
                ),
                (
                    "target_pages",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of page slugs (e.g., 'home,services,team'). Leave empty to show on all pages.",
                        verbose_name="Target Pages",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority promos are shown first if multiple are active (higher number = higher priority)",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="#EDD071",
                        help_text="Hex color code (e.g., #EDD071)",
                        max_length=7,
                        verbose_name="Button Background Color",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#003831",
                        help_text="Hex color code (e.g., #003831)",
                        max_length=7,
                        verbose_name="Button Text Color",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image to display in the modal window",
                        null=True,
                        upload_to="promos/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times the floating button was displayed",
                        verbose_name="Views Count",
                    ),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times the modal window was opened", verbose_name="Clicks Count"
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo Notification",
                "verbose_name_plural": "Promo Notifications",
                "ordering": ["-priority", "-starts_at"],
            },
        ),
    ]
