# Generated by Django 5.2.11 on 2026-02-13 12:06

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="StaticPageSeo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, help_text="Meta description for search engines.", verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_de",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Home Page"),
                            ("contacts", "Contacts Page"),
                            ("team", "Team Page"),
                            ("services_index", "Services List"),
                            ("impressum", "Impressum"),
                            ("datenschutz", "Privacy Policy"),
                        ],
                        help_text="Unique key to identify the page in code",
                        max_length=50,
                        unique=True,
                        verbose_name="Page Identifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page SEO",
                "verbose_name_plural": "Static Page SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company_name",
                    models.CharField(default="LILY Beauty Salon", max_length=255, verbose_name="Company Name"),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255, verbose_name="Owner Name")),
                ("tax_number", models.CharField(blank=True, max_length=100, verbose_name="Tax Number (Steuernummer)")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone Number")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email Address")),
                ("address_street", models.CharField(blank=True, max_length=255, verbose_name="Street & House Number")),
                ("address_city", models.CharField(blank=True, max_length=255, verbose_name="Postal Code & City")),
                (
                    "address_city_de",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Postal Code & City"),
                ),
                (
                    "address_city_ru",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Postal Code & City"),
                ),
                (
                    "address_city_uk",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Postal Code & City"),
                ),
                (
                    "address_city_en",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Postal Code & City"),
                ),
                ("google_maps_link", models.URLField(blank=True, verbose_name="Google Maps Link")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram URL")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram URL")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp URL")),
                (
                    "working_hours_weekdays",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '09:00 - 18:00'",
                        max_length=100,
                        verbose_name="Working Hours (Mon-Fri)",
                    ),
                ),
                (
                    "working_hours_weekdays_de",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '09:00 - 18:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Mon-Fri)",
                    ),
                ),
                (
                    "working_hours_weekdays_ru",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '09:00 - 18:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Mon-Fri)",
                    ),
                ),
                (
                    "working_hours_weekdays_uk",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '09:00 - 18:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Mon-Fri)",
                    ),
                ),
                (
                    "working_hours_weekdays_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '09:00 - 18:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Mon-Fri)",
                    ),
                ),
                (
                    "working_hours_saturday",
                    models.CharField(
                        blank=True, help_text="e.g. '10:00 - 14:00'", max_length=100, verbose_name="Working Hours (Sat)"
                    ),
                ),
                (
                    "working_hours_saturday_de",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10:00 - 14:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Sat)",
                    ),
                ),
                (
                    "working_hours_saturday_ru",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10:00 - 14:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Sat)",
                    ),
                ),
                (
                    "working_hours_saturday_uk",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10:00 - 14:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Sat)",
                    ),
                ),
                (
                    "working_hours_saturday_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10:00 - 14:00'",
                        max_length=100,
                        null=True,
                        verbose_name="Working Hours (Sat)",
                    ),
                ),
                (
                    "working_hours_sunday",
                    models.CharField(blank=True, default="Closed", max_length=100, verbose_name="Working Hours (Sun)"),
                ),
                (
                    "working_hours_sunday_de",
                    models.CharField(
                        blank=True, default="Closed", max_length=100, null=True, verbose_name="Working Hours (Sun)"
                    ),
                ),
                (
                    "working_hours_sunday_ru",
                    models.CharField(
                        blank=True, default="Closed", max_length=100, null=True, verbose_name="Working Hours (Sun)"
                    ),
                ),
                (
                    "working_hours_sunday_uk",
                    models.CharField(
                        blank=True, default="Closed", max_length=100, null=True, verbose_name="Working Hours (Sun)"
                    ),
                ),
                (
                    "working_hours_sunday_en",
                    models.CharField(
                        blank=True, default="Closed", max_length=100, null=True, verbose_name="Working Hours (Sun)"
                    ),
                ),
                ("work_start_weekdays", models.TimeField(default="09:00:00", verbose_name="Work Start (Mon-Fri)")),
                ("work_end_weekdays", models.TimeField(default="18:00:00", verbose_name="Work End (Mon-Fri)")),
                ("work_start_saturday", models.TimeField(default="10:00:00", verbose_name="Work Start (Sat)")),
                ("work_end_saturday", models.TimeField(default="14:00:00", verbose_name="Work End (Sat)")),
                (
                    "hiring_active",
                    models.BooleanField(
                        default=False,
                        help_text="Show hiring badge and section on the site",
                        verbose_name="Hiring Active",
                    ),
                ),
                ("hiring_title", models.CharField(blank=True, max_length=255, verbose_name="Hiring Title")),
                (
                    "hiring_title_de",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Hiring Title"),
                ),
                (
                    "hiring_title_ru",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Hiring Title"),
                ),
                (
                    "hiring_title_uk",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Hiring Title"),
                ),
                (
                    "hiring_title_en",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Hiring Title"),
                ),
                ("hiring_text", models.TextField(blank=True, verbose_name="Hiring Text")),
                ("hiring_text_de", models.TextField(blank=True, null=True, verbose_name="Hiring Text")),
                ("hiring_text_ru", models.TextField(blank=True, null=True, verbose_name="Hiring Text")),
                ("hiring_text_uk", models.TextField(blank=True, null=True, verbose_name="Hiring Text")),
                ("hiring_text_en", models.TextField(blank=True, null=True, verbose_name="Hiring Text")),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
