# Generated by Django 5.2.11 on 2026-02-14 09:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticpageseo",
            options={"verbose_name": "Static Page SEO", "verbose_name_plural": "Static Pages SEO"},
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_city",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_city_de",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_city_en",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_city_ru",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="address_city_uk",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality",
            field=models.CharField(default="Köthen (Anhalt)", max_length=255, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality_de",
            field=models.CharField(default="Köthen (Anhalt)", max_length=255, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality_en",
            field=models.CharField(default="Köthen (Anhalt)", max_length=255, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality_ru",
            field=models.CharField(default="Köthen (Anhalt)", max_length=255, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality_uk",
            field=models.CharField(default="Köthen (Anhalt)", max_length=255, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_postal_code",
            field=models.CharField(default="06366", max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default="51.746495", max_digits=9, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default="11.9784666", max_digits=9, verbose_name="Longitude"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="price_range",
            field=models.CharField(default="$$", max_length=10, verbose_name="Price Range"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_base_url",
            field=models.URLField(default="https://lily-salon.de/", verbose_name="Site Base URL"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_street",
            field=models.CharField(default="Lohmannstraße 111", max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(default="info@lily-salon.de", max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="google_maps_link",
            field=models.URLField(
                blank=True, help_text="Link to open location in Maps", verbose_name="Google Maps Link"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_active",
            field=models.BooleanField(
                default=True, help_text="Show 'We are hiring' block on Team page", verbose_name="Hiring Active"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_text",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_text_de",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_text_en",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_text_ru",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_text_uk",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_title",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, verbose_name="Hiring Title"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_title_de",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_title_en",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_title_ru",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hiring_title_uk",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="https://instagram.com/manikure_kothen", verbose_name="Instagram URL"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="owner_name",
            field=models.CharField(default="Liliia Yakina", max_length=255, verbose_name="Owner Name"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(default="+49 176 59423704", max_length=50, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="work_end_saturday",
            field=models.TimeField(default=datetime.time(14, 0), verbose_name="Saturday End"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="work_end_weekdays",
            field=models.TimeField(default=datetime.time(18, 0), verbose_name="Mo-Fr End"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="work_start_saturday",
            field=models.TimeField(default=datetime.time(10, 0), verbose_name="Saturday Start"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="work_start_weekdays",
            field=models.TimeField(default=datetime.time(9, 0), verbose_name="Mo-Fr Start"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday",
            field=models.CharField(default="10:00 - 14:00", max_length=100, verbose_name="Saturday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_de",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_en",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_ru",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_saturday_uk",
            field=models.CharField(
                default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday",
            field=models.CharField(default="Geschlossen", max_length=100, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_de",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_en",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_ru",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_sunday_uk",
            field=models.CharField(default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays",
            field=models.CharField(default="09:00 - 18:00", max_length=100, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_de",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_en",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_ru",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="working_hours_weekdays_uk",
            field=models.CharField(default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"),
        ),
        migrations.AlterField(
            model_name="staticpageseo",
            name="page_key",
            field=models.CharField(
                choices=[
                    ("home", "Home Page"),
                    ("contacts", "Contacts Page"),
                    ("team", "Team Page"),
                    ("services_index", "Services List Page"),
                    ("impressum", "Impressum"),
                    ("datenschutz", "Datenschutz"),
                ],
                help_text="Unique identifier for the static page.",
                max_length=50,
                unique=True,
                verbose_name="Page Key",
            ),
        ),
    ]
