# Generated by Django 5.2.11 on 2026-02-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_alter_staticpageseo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo_url",
            field=models.URLField(blank=True, default="/static/img/logo_lily.webp", verbose_name="Logo URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="url_path_cancel",
            field=models.CharField(
                default="/appointments/cancel/{token}/", max_length=255, verbose_name="Booking Cancel URL Path"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="url_path_confirm",
            field=models.CharField(
                default="/appointments/confirm/{token}/", max_length=255, verbose_name="Booking Confirm URL Path"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="url_path_contact_form",
            field=models.CharField(default="/contacts/", max_length=255, verbose_name="Contact Form URL Path"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="url_path_reschedule",
            field=models.CharField(default="/booking/", max_length=255, verbose_name="Booking Reschedule URL Path"),
        ),
    ]
