# Generated by Django 5.2.11 on 2026-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_alter_sitesettings_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier used in templates (e.g., 'home_hero_title')",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The actual text to be displayed and translated.", verbose_name="Text Content"
                    ),
                ),
                (
                    "text_de",
                    models.TextField(
                        help_text="The actual text to be displayed and translated.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        help_text="The actual text to be displayed and translated.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_uk",
                    models.TextField(
                        help_text="The actual text to be displayed and translated.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        help_text="The actual text to be displayed and translated.",
                        null=True,
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional note about where this text is used.",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Translation",
                "verbose_name_plural": "Static Translations",
                "ordering": ["key"],
            },
        ),
    ]
