import os
import re

# 1. Наши новые смысловые ключи
MAPPING = {
    "nav_main_home": {"de": "Startseite", "ru": "Главная", "uk": "Головна", "en": "Home"},
    "nav_main_services": {"de": "Leistungen", "ru": "Услуги", "uk": "Послуги", "en": "Services"},
    "nav_main_team": {"de": "Team", "ru": "Команда", "uk": "Команда", "en": "Team"},
    "nav_main_contacts": {"de": "Kontakt", "ru": "Контакты", "uk": "Контакти", "en": "Contacts"},
    "nav_footer_all_contacts": {
        "de": "Alle Kontakte",
        "ru": "Все контакты",
        "uk": "Всі контакти",
        "en": "All Contacts",
    },
    "nav_legal_impressum": {"de": "Impressum", "ru": "Импрессум", "uk": "Імпрессум", "en": "Imprint"},
    "nav_legal_privacy": {"de": "Datenschutz", "ru": "Конфиденциальность", "uk": "Конфіденційність", "en": "Privacy"},
    "nav_legal_cookies": {
        "de": "Cookie-Einstellungen",
        "ru": "Настройки куки",
        "uk": "Налаштування кукі",
        "en": "Cookie Settings",
    },
    "btn_cta_booking": {"de": "Termin buchen", "ru": "Записаться", "uk": "Записатися", "en": "Book Now"},
    "btn_action_more": {"de": "Mehr erfahren", "ru": "Подробнее", "uk": "Детальніше", "en": "Learn More"},
    "btn_ui_toggle_footer": {
        "de": "Toggle Footer",
        "ru": "Показать футер",
        "uk": "Показати футер",
        "en": "Toggle Footer",
    },
    "service_cat_hair": {
        "de": "Frisuren & Haarpflege",
        "ru": "Прически и уход",
        "uk": "Зачіски та догляд",
        "en": "Hair & Care",
    },
    "service_cat_nails": {
        "de": "Nagelservice",
        "ru": "Ногтевой сервис",
        "uk": "Нігтьовий сервіс",
        "en": "Nail Service",
    },
    "service_cat_beauty": {
        "de": "Schönheit & Pflege",
        "ru": "Красота и уход",
        "uk": "Краса та догляд",
        "en": "Beauty & Care",
    },
    "label_address": {"de": "Unsere Adresse", "ru": "Наш адрес", "uk": "Наша адреса", "en": "Our Address"},
    "label_phone": {"de": "Telefon", "ru": "Телефон", "uk": "Телефон", "en": "Phone"},
    "label_email": {"de": "E-Mail", "ru": "E-Mail", "uk": "E-Mail", "en": "E-Mail"},
    "label_working_hours": {"de": "Öffnungszeiten", "ru": "Часы работы", "uk": "Години роботи", "en": "Opening Hours"},
    "btn_action_route": {
        "de": "Route planen",
        "ru": "Проложить маршрут",
        "uk": "Прокласти маршрут",
        "en": "Get Directions",
    },
    "btn_action_book": {"de": "Buchen", "ru": "Забронировать", "uk": "Забронювати", "en": "Book"},
    "btn_action_apply": {"de": "Bewerben", "ru": "Откликнуться", "uk": "Відгукнутися", "en": "Apply"},
    "label_price_list": {"de": "Preisliste", "ru": "Прайс-лист", "uk": "Прайс-лист", "en": "Price List"},
    "label_why_us": {"de": "Warum wir?", "ru": "Почему мы?", "uk": "Чому ми?", "en": "Why us?"},
    "service_item_cosmetology": {
        "de": "Gesichtskosmetik",
        "ru": "Косметология лица",
        "uk": "Косметологія обличчя",
        "en": "Facial Cosmetology",
    },
    "service_item_depilation": {"de": "Epilation", "ru": "Эпиляция", "uk": "Епіляція", "en": "Depilation"},
    "service_item_lashes": {
        "de": "Wimpernverlängerung",
        "ru": "Наращивание ресниц",
        "uk": "Нарощування вій",
        "en": "Lash Extensions",
    },
    "service_item_massage": {"de": "Massage", "ru": "Массаж", "uk": "Масаж", "en": "Massage"},
    "service_item_haircuts": {"de": "Haarschnitte", "ru": "Стрижки", "uk": "Стрижки", "en": "Haircuts"},
    "service_item_coloring": {"de": "Färben", "ru": "Окрашивание", "uk": "Фарбування", "en": "Coloring"},
    "service_item_treatment": {
        "de": "Haarbehandlung",
        "ru": "Уход за волосами",
        "uk": "Догляд за волоссям",
        "en": "Hair Treatment",
    },
    "service_item_styling": {"de": "Styling", "ru": "Стайлинг", "uk": "Стайлінг", "en": "Styling"},
    "service_item_manicure": {"de": "Maniküre", "ru": "Маникюр", "uk": "Манікюр", "en": "Manicure"},
    "service_item_pedicure": {"de": "Pediküre", "ru": "Педикюр", "uk": "Педикюр", "en": "Pedicure"},
    "service_item_extension": {"de": "Verlängerung", "ru": "Наращивание", "uk": "Нарощування", "en": "Extension"},
    "service_item_lamination": {"de": "Laminierung", "ru": "Ламинирование", "uk": "Ламінування", "en": "Lamination"},
    "btn_ui_show_promo": {
        "de": "Promotion anzeigen",
        "ru": "Показать акцию",
        "uk": "Показати акцію",
        "en": "Show Promotion",
    },
    "btn_action_close": {"de": "Schließen", "ru": "Закрыть", "uk": "Закрити", "en": "Close"},
    "label_founder_master": {
        "de": "Founder & Master",
        "ru": "Основатель и Мастер",
        "uk": "Засновник та Майстер",
        "en": "Founder & Master",
    },
    "label_your_experts": {"de": "Ihre Experten", "ru": "Ваши эксперты", "uk": "Ваші експерти", "en": "Your Experts"},
    "msg_no_services_found": {
        "de": "Keine Dienstleistungen gefunden.",
        "ru": "Услуги не найдены.",
        "uk": "Послуг не знайдено.",
        "en": "No services found.",
    },
    "label_service": {"de": "Leistung", "ru": "Услуга", "uk": "Послуга", "en": "Service"},
}

# 2. Системные строки, которые пострадали при перезаписи немецкого файла
RECOVERY_DE = {
    "Basic Info": "Grundinformationen",
    "Professional": "Berufsbezeichnung",
    "Contacts": "Kontakt",
    "System": "System",
    "SEO": "SEO",
    "Status": "Status",
    "Promo": "Promo",
    "Mark as Confirmed": "Als bestätigt markieren",
    "Client": "Kunde",
    "Master": "Meister",
    "Service": "Service",
    "Start Date & Time": "Startdatum & -zeit",
    "Appointment start time": "Termin-Startzeit",
    "Duration (minutes)": "Dauer (Min)",
    "Service duration (auto-filled from Service model)": "Dauer der Dienstleistung (automatisch ausgefüllt)",
    "Price (€)": "Preis (€)",
    "Price at booking time (snapshot)": "Preis zum Zeitpunkt der Buchung",
    "Pending Confirmation": "Ausstehende Bestätigung",
    "Confirmed": "Bestätigt",
    "Completed": "Abgeschlossen",
    "Cancelled": "Storniert",
    "No Show": "Nicht erschienen",
    "Website": "Webseite",
    "Telegram Bot": "Telegram Bot",
    "Phone": "Telefon",
    "Admin Panel": "Admin-Bereich",
    "Booking Source": "Buchungsquelle",
    "Where this appointment was created": "Wo dieser Termin erstellt wurde",
    "Cancelled At": "Storniert am",
    "Cancelled by Client": "Vom Kunden storniert",
    "Cancelled by Master": "Vom Meister storniert",
    "Rescheduled": "Verschoben",
    "Other": "Sonstiges",
    "Cancellation Reason": "Stornierungsgrund",
    "Cancellation Note": "Stornierungsnotiz",
    "Additional details about cancellation": "Zusätzliche Details zur Stornierung",
    "Client Notes": "Anmerkungen des Kunden",
    "Special requests from client (e.g. allergies, preferences)": "Besondere Wünsche des Kunden",
    "Admin Notes": "Admin-Notizen",
    "Internal notes (not visible to client)": "Interne Notizen (für Kunden nicht sichtbar)",
    "Reminder Sent": "Erinnerung gesendet",
    "SMS/Email reminder was sent": "SMS/E-Mail-Erinnerung wurde gesendet",
    "Reminder Sent At": "Erinnerung gesendet am",
    "Active Promo": "Aktive Aktion",
    "Promo that was active when booking was made": "Aktion, die bei der Buchung aktiv war",
    "Appointment": "Termin",
    "Appointments": "Termine",
    "This time slot is already booked.": "Zeitfenster ist bereits belegt.",
    "This appointment cannot be cancelled.": "Dieser Termin kann nicht storniert werden.",
    "Only confirmed appointments can be marked as completed.": "Nur bestätigte Termine können als abgeschlossen markiert werden.",
    "Phone Number": "Telefonnummer",
    "Primary contact method": "Primäre Kontaktmethode",
    "Email": "E-Mail",
    "Email for notifications and account activation": "E-Mail für Benachrichtigungen",
    "First Name": "Vorname",
    "Last Name": "Nachname",
    "Instagram": "Instagram",
    "Username or link": "Benutzername oder Link",
    "Telegram": "Telegram",
    "Django User Account": "Django-Benutzerkonto",
    "Linked when client activates account": "Verknüpft, wenn der Kunde das Konto aktiviert",
    "Access Token": "Zugriffstoken",
    "Used in SMS/Email links for appointment management": "Wird in SMS/E-Mail-Links verwendet",
    "Guest (Temporary)": "Gast (temporär)",
    "Active (Registered)": "Aktiv (registriert)",
    "Blocked": "Gesperrt",
    "Marketing Consent": "Marketing-Einwilligung",
    "Client agreed to receive promotional materials": "Kunde hat dem Erhalt von Werbematerialien zugestimmt",
    "Consent Given Date": "Datum der Einwilligung",
    "Internal Notes": "Interne Notizen",
    "Admin-only notes about the client": "Notizen nur für Admin",
    "Clients": "Kunden",
    "Guest": "Gast",
    "Full Name": "Vollständiger Name",
    "Master's full name (e.g. 'Maria Ivanova')": "Vollständiger Name des Meisters",
    "Slug": "Slug",
    "URL part (e.g. 'maria-ivanova')": "URL-Teil",
    "Profile Photo": "Profilfoto",
    "Professional portrait (recommended: 800x1000px)": "Professionelles Porträt",
    "Professional Title": "Berufsbezeichnung",
    "e.g. 'Top Colorist', 'Lead Nail Artist'": "z.B. 'Top Colorist'",
    "Biography": "Biografie",
    "Full biography and work philosophy (HTML allowed)": "Vollständige Biografie",
    "Short Description": "Kurzbeschreibung",
    "Brief intro for Team page (1-2 sentences)": "Kurze Einführung für die Team-Seite",
    "Categories": "Kategorien",
    "High-level categories for filtering": "Hauptкатегории для Filter",
    "Years of Experience": "Berufserfahrung (Jahre)",
    "Instagram Handle": "Instagram-Name",
    "Username only (e.g. 'maria.beauty')": "Nur Benutzername",
    "Direct Phone": "Direkte Telefonnummer",
    "Active (Working)": "Aktiv (arbeitend)",
    "On Vacation": "Im Urlaub",
    "Fired/Left": "Ausgeschieden",
    "In Training": "In Ausbildung",
    "Employment Status": "Beschäftigungsstatus",
    "We never delete masters, only change status": "Wir löschen keine Meister, wir ändern nur den Status",
    "Is Owner": "Ist Inhaber",
    "Display as salon owner with special styling": "Als Saloninhaber anzeigen",
    "Featured Master": "Besonderer Meister",
    "Display Order": "Anzeigereihenfolge",
    "Lower numbers appear first": "Kleinere Zahlen erscheinen zuerst",
    "Linked when master needs personal cabinet access": "Verknüpft für Kabinett-Zugriff",
    "Telegram ID": "Telegram ID",
    "For 02_telegram_bot authentication and notifications": "Für Bot-Authentifizierung",
    "Telegram Username": "Telegram Benutzername",
    "Bot Access Code": "Bot-Zugangscode",
    "One-time code for master registration in 02_telegram_bot": "Einmaliger Code für Bot-Registrierung",
    "QR Token": "QR Token",
    "Masters": "Meister",
    "Certificate Title": "Zertifikatstitel",
    "e.g. 'Advanced Nail Art Course'": "z.B. 'Fortgeschrittener Nagelkurs'",
    "Issuing Organization": "Ausstellende Organisation",
    "e.g. 'German Beauty Academy'": "z.B. 'Deutsche Beauty Akademie'",
    "Issue Date": "Ausstellungsdatum",
    "Certificate Image": "Zertifikatsbild",
    "Scan or photo of certificate (recommended: 1200x900px)": "Scan oder Foto des Zertifikats",
    "Active": "Aktiv",
    "Show on master page": "Auf der Meisterseite anzeigen",
    "Master Certificate": "Meister-Zertifikat",
    "Master Certificates": "Meister-Zertifikate",
    "Date": "Datum",
    "Reason": "Grund",
    "Master Day Off": "Ruhetag des Meisters",
    "Master Days Off": "Ruhetage des Meisters",
    "Portfolio Image": "Portfolio-Bild",
    "Example of master's work (recommended: 1200x1200px)": "Beispiel der Arbeit",
    "Description": "Beschreibung",
    "Brief description of the work (technique, products used, etc.)": "Kurze Beschreibung der Arbeit",
    "Related Service": "Zugehörige Dienstleistung",
    "Link to service this example demonstrates": "Link zur Dienstleistung",
    "Instagram Post URL": "Instagram Post URL",
    "Link to original Instagram post": "Link zum Original-Post",
    "Portfolio Item": "Portfolio-Element",
    "Portfolio Items": "Portfolio-Elemente",
    "General work": "Allgemeine Arbeit",
    "Leistung": "Leistung",
    "Experte": "Experte",
    "Termin": "Termin",
    "Bestätigung": "Bestätigung",
    "Content": "Inhalt",
    "Pricing & Duration": "Preise & Dauer",
    "E-Mail": "E-Mail",
    "Vorname": "Vorname",
    "Nachname": "Nachname",
    "Kontaktart": "Kontaktart",
    "Kontakt": "Kontakt",
    "Ihre E-Mail-Adresse": "Ihre E-Mail-Adresse",
    "Thema": "Thema",
    "Nachricht": "Nachricht",
    "Ihre Nachricht...": "Ihre Nachricht...",
    "Ich möchte über Neuigkeiten und Angebote informiert werden.": "Ich möchte über Neuigkeiten und Angebote informiert werden.",
    "Bitte geben Sie eine gültige E-Mail-Adresse ein.": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "Friseur & Styling": "Friseur & Styling",
    "Nagelservice": "Nagelservice",
    "Kosmetologie": "Kosmetologie",
    "Brows & Lashes": "Brows & Lashes",
    "Massage & Relax": "Massage & Relax",
    "Depilation": "Depilation",
    "Title": "Titel",
    "Category name (e.g. 'Maniküre').": "Kategoriename (z.B. 'Maniküre').",
    "Bento Group": "Bento-Gruppe",
    "Image": "Bild",
    "Background image for Hero section and Bento card.": "Hintergrundbild",
    "SEO Text / Content": "SEO Text / Inhalt",
    "Detailed text displayed at the bottom of the category page.": "Detaillierter Text",
    "Icon": "Icon",
    "SVG icon for menu or footer (optional).": "SVG-Icon",
    "Order": "Reihenfolge",
    "Sorting order (lower numbers come first).": "Sortierreihenfolge",
    "Category": "Kategorie",
    "General Question": "Allgemeine Frage",
    "Questions about Booking": "Fragen zur Buchung",
    "Job / Career": "Job / Karriere",
    "Topic": "Thema",
    "Message": "Nachricht",
    "Processed": "Verarbeitet",
    "Contact Request": "Kontaktanfrage",
    "Contact Requests": "Kontaktanfragen",
    "Main category (for filtering).": "Hauptkategorie",
    "Base price for sorting and calculation.": "Basispreis",
    "Price Display Text": "Preis-Anзеigetext",
    "Duration (min)": "Dauer (Min)",
    "Duration in minutes.": "Dauer in Minuten.",
    "Duration Display Text": "Dauer-Anzeigetext",
    "Full Content": "Vollständiger Inhalt",
    "Detailed description/article about the service (HTML/Markdown).": "Detaillierte Beschreibung",
    "Hit / Popular": "Hit / Beliebt",
    "Highlight this service as popular.": "Diese Leistung als beliebt markieren.",
    "Services": "Leistungen",
    "Portfolio Images": "Portfolio-Bilder",
    "Scheduling": "Zeitplanung",
    "Targeting": "Targeting",
    "Design": "Design",
    "Statistics": "Statistiken",
    "Metadata": "Metadaten",
    "Scheduled": "Geplant",
    "Expired": "Abgelaufen",
    "Inactive": "Inaktiv",
    "Button Preview": "Button-Vorschau",
    "No views yet": "Noch keine Aufrufe",
    "Date Range": "Datumsbereich",
    "CTR": "CTR",
    "Activate selected promos": "Ausgewählte Aktionen aktivieren",
    "Deactivate selected promos": "Ausgewählte Aktionen deaktivieren",
    "Promos": "Aktionen",
    "Main title of the promotion": "Haupttitel der Aktion",
    "Full description shown in the modal window": "Vollständige Beschreibung",
    "Button Text": "Button-Text",
    "Text displayed on the floating button": "Text auf dem schwebenden Button",
    "Start Date": "Startdatum",
    "End Date": "Enddatum",
    "Display Delay (seconds)": "Anzeigeverzögerung (Sekunden)",
    "Target Pages": "Zielseiten",
    "Priority": "Priorität",
    "Button Background Color": "Button-Hintergrundfarbe",
    "Button Text Color": "Button-Textfarbe",
    "Views Count": "Anzahl der Aufrufe",
    "Clicks Count": "Anzahl der Klicks",
    "Promo Notification": "Aktions-Benachrichtigung",
    "Promo Notifications": "Aktions-Benachrichtigungen",
    "End date must be after start date": "Enddatum muss nach dem Startdatum liegen",
    "Identification": "Identifikation",
    "Translations": "Übersetzungen",
    "Text Preview": "Textvorschau",
    "SEO Optimization": "SEO-Optimierung",
    "Page Identification": "Seitenidentifikation",
    "SEO Title": "SEO-Titel",
    "OG Image": "OG-Bild",
    "General Information": "Allgemeine Informationen",
    "Contact Details": "Kontaktdaten",
    "Social Media": "Social Media",
    "Working Hours": "Öffnungszeiten",
    "Analytics & Marketing": "Analyse & Marketing",
    "Hiring / Vacancies": "Jobs / Stellenangebote",
    "Technical URL Paths": "Technische URL-Pfade",
    "Created at": "Erstellt am",
    "Updated at": "Aktualisiert am",
    "Available for Booking": "Für Buchung verfügbar",
    "Planned / Coming Soon": "Geplant / Demnächst",
    "SEO Description": "SEO-Beschreibung",
    "Home Page": "Startseite",
    "Contacts Page": "Kontaktseite",
    "Team Page": "Teamseite",
    "Services List Page": "Leistungsübersicht",
    "Impressum": "Impressum",
    "Datenschutz": "Datenschutz",
    "Page Key": "Seitenschlüssel",
    "Static Page SEO": "SEO для statische Seiten",
    "Static Pages SEO": "SEO для statische Seiten",
    "Company Name": "Firmenname",
    "Owner Name": "Inhabername",
    "Tax Number (Steuernummer)": "Steuernummer",
    "Site Base URL": "Basis-URL der Seite",
    "Logo URL": "Logo-URL",
    "Street": "Straße",
    "City": "Stadt",
    "PLZ": "PLZ",
    "Google Maps Link": "Google Maps Link",
    "Latitude": "Breitengrad",
    "Longitude": "Längengrad",
    "Instagram URL": "Instagram URL",
    "Telegram URL": "Telegram URL",
    "WhatsApp URL": "WhatsApp URL",
    "Facebook URL": "Facebook URL",
    "Telegram Bot Username": "Telegram Bot Benutzername",
    "Mo-Fr (Display)": "Mo-Fr (Anzeige)",
    "Saturday (Display)": "Samstag (Anzeige)",
    "Sunday (Display)": "Sonntag (Anzeige)",
    "Mo-Fr Start": "Mo-Fr Beginn",
    "Mo-Fr End": "Mo-Fr Ende",
    "Saturday Start": "Samstag Beginn",
    "Saturday End": "Samstag Ende",
    "Price Range": "Preisklasse",
    "Contact Form URL Path": "Kontaktformular URL-Pfad",
    "Booking Confirm URL Path": "Buchungsbestätigung URL-Pfad",
    "Booking Cancel URL Path": "Buchungsstornierung URL-Pfad",
    "Booking Reschedule URL Path": "Buchungsverschiebung URL-Pfad",
    "Hiring Active": "Jobs aktiv",
    "Hiring Title": "Job-Titel",
    "Hiring Text": "Job-Text",
    "Google Analytics ID": "Google Analytics ID",
    "Google Tag Manager ID": "Google Tag Manager ID",
    "Site Settings": "Seiteneinstellungen",
    "Key": "Schlüssel",
    "Text Content": "Textinhalt",
    "Static Translation": "Statische Übersetzung",
    "Static Translations": "Statische Übersetzungen",
    "Ungültige Anfrage": "Ungültige Anfrage",
    "Der Server konnte Ihre Anfrage nicht verarbeiten.": "Der Server konnte Ihre Anfrage nicht verarbeiten.",
    "Zur Startseite": "Zur Startseite",
    "Zugriff verweigert": "Zugriff verweigert",
    "Sie haben keine Berechtigung, diese Seite aufzurufen.": "Sie haben keine Berechtigung, diese Seite aufzurufen.",
    "Seite nicht gefunden": "Seite nicht gefunden",
    "Die von Ihnen gesuchte Seite existiert leider nicht oder wurde verschoben.": "Die von Ihnen gesuchte Seite existiert leider nicht oder wurde verschoben.",
    "Serverfehler": "Serverfehler",
    "Interner Serverfehler": "Interner Serverfehler",
    "Es ist ein Fehler aufgetreten. Wir arbeiten bereits daran.": "Es ist ein Fehler aufgetreten. Wir arbeiten bereits daran.",
    "Termin stornieren": "Termin stornieren",
    "Möchten Sie diesen Termin wirklich stornieren?": "Möchten Sie diesen Termin wirklich stornieren?",
    "Diese Aktion kann nicht rückgängig gemacht werden.": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Ja, Termin stornieren": "Ja, Termin stornieren",
    "Nein, zurück zur Startseite": "Nein, zurück zur Startseite",
    "Termin erfolgreich storniert": "Termin erfolgreich storniert",
    "Ihr Termin wurde erfolgreich storniert.": "Ihr Termin wurde erfolgreich storniert.",
    "Wir hoffen, Sie bald wieder bei uns begrüßen zu dürfen.": "Wir hoffen, Sie bald wieder bei uns begrüßen zu dürfen.",
    "Termin bestätigen": "Termin bestätigen",
    "Ihre Terminbestätigung": "Ihre Terminbestätigung",
    "Vielen Dank! Ihr Termin wurde erfolgreich bestätigt.": "Vielen Dank! Ihr Termin wurde erfolgreich bestätigt.",
    "Sie erhalten in Kürze eine Bestätigungs-E-Mail.": "Sie erhalten in Kürze eine Bestätigungs-E-Mail.",
    "Ihr Termin": "Ihr Termin",
    "Bitte wählen Sie zuerst eine Leistung aus.": "Bitte wählen Sie zuerst eine Leistung aus.",
    "Zeit": "Zeit",
    "Gesamt": "Gesamt",
    "Termin verschieben": "Termin verschieben",
    "Hier können Sie Ihren Termin verschieben oder ein neues Zeitfenster wählen.": "Hier können Sie Ihren Termin verschieben oder ein neues Zeitfenster wählen.",
    "Bitte wählen Sie unten einen neuen Termin aus.": "Bitte wählen Sie unten einen neuen Termin aus.",
    "Neuen Termin wählen": "Neuen Termin wählen",
    "Wählen Sie eine Leistung": "Wählen Sie eine Leistung",
    "Auswählen": "Auswählen",
    "Keine Leistungen in dieser Kategorie gefunden.": "Keine Leistungen in dieser Kategorie gefunden.",
    "Wählen Sie einen Experten": "Wählen Sie einen Experten",
    "Zurück": "Zurück",
    "Beliebiger Experte": "Beliebiger Experte",
    "Frühestmöglicher Termin": "Frühestmöglicher Termin",
    "Leider sind für diese Leistung aktuell keine Experten verfügbar.": "Leider sind für diese Leistung aktuell keine Experten verfügbar.",
    "Wählen Sie einen Termin": "Wählen Sie einen Termin",
    "Verfügbare Zeit am": "Verfügbare Zeit am",
    "Keine freien Termine.": "Keine freien Termine.",
    "Bitte wählen Sie ein Datum.": "Bitte wählen Sie ein Datum.",
    "Ihre Daten": "Ihre Daten",
    "Telefonnummer": "Telefonnummer",
    "Anmerkungen (Optional)": "Anmerkungen (Optional)",
    "Bitte teilen Sie uns Ihre Wünsche, Besonderheiten oder Allergien mit...": "Bitte teilen Sie uns Ihre Wünsche, Besonderheiten oder Allergien mit...",
    "Bitte rufen Sie mich zur Bestätigung an": "Bitte rufen Sie mich zur Bestätigung an",
    "Ich stimме zu, dass meine Daten gespeichert werden und ich Benachrichtigungen (SMS/E-Mail) zu meinem Termin erhalte.": "Ich stimme zu, dass meine Daten gespeichert werden und ich Benachrichtigungen (SMS/E-Mail) zu meinem Termin erhalte.",
    "Termin verbindlich buchen": "Termin verbindlich buchen",
    "Vielen Dank!": "Vielen Dank!",
    "Ihr Termin wurde erfolgreich gebucht. Wir haben Ihnen eine Bestätigung per E-Mail gesendet.": "Ihr Termin wurde erfolgreich gebucht. Wir haben Ihnen eine Bestätigung per E-Mail gesendet.",
    "bei": "bei",
    "Zurück zur Startseite": "Zurück zur Startseite",
    "Termin buchen": "Termin buchen",
    "Online Terminbuchung": "Online Terminbuchung",
    "IN WENIGEN SCHRITTEN ZUM TERMIN": "IN WENIGEN SCHRITTEN ZUM TERMIN",
    "Name": "Name",
    "Absenden": "Absenden",
    "Ihre Nachricht wurde gesendet. Wir werden uns in Kürze bei Ihnen melden.": "Ihre Nachricht wurde gesendet. Wir werden uns in Kürзе bei Ihnen melden.",
    "Zu viele Anfragen": "Zu viele Anfragen",
    "Bitte warten Sie einen Moment, bevor Sie es erneut versuchen. Wir schützen unser System vor automatisierten Anfragen.": "Bitte warten Sie einen Moment, bevor Sie es erneut versuchen.",
    "Online-Terminbuchung": "Online-Terminbuchung",
    "Beauty Services": "Beauty Services",
    "Demnächst": "Demnächst",
    "Cookies & Datenschutz": "Cookies & Datenschutz",
    "Nur essenzielle": "Nur essenzielle",
    "Alle akzeptieren": "Alle akzeptieren",
}


def fix_po(lang):
    path = f"src/backend_django/locale/{lang}/LC_MESSAGES/django.po"
    if not os.path.exists(path):
        return

    with open(path, encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    current_msgid = None

    for line in lines:
        msgid_match = re.match(r'^msgid "(.*)"', line)
        if msgid_match:
            current_msgid = msgid_match.group(1)
            new_lines.append(line)
            continue

        msgstr_match = re.match(r'^msgstr "(.*)"', line)
        if msgstr_match:
            # Сначала проверяем наши новые ключи
            if current_msgid in MAPPING:
                translation = MAPPING[current_msgid].get(lang, "")
                new_lines.append(f'msgstr "{translation}"\n')
            # Если это немецкий файл, восстанавливаем системные строки
            elif lang == "de" and current_msgid in RECOVERY_DE:
                new_lines.append(f'msgstr "{RECOVERY_DE[current_msgid]}"\n')
            else:
                new_lines.append(line)
            current_msgid = None
            continue

        new_lines.append(line)

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)
    print(f"Fixed and Recovered {lang}")


for lang in ["de", "en", "ru", "uk"]:
    fix_po(lang)
