"""Scaffold-owned provider entrypoints for resource-slot booking.

This package is intended to be generated by the booking scaffold. Project
owners can replace the default provider binding with their own provider or
inherit from the scaffold provider to keep the runtime contracts stable.
"""

from .runtime import RuntimeBookingProvider, get_booking_project_data_provider

__all__ = ["RuntimeBookingProvider", "get_booking_project_data_provider"]
