# Generated by Django 5.2.13 on 2026-04-18 14:17

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[Any] = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: list[migrations.operations.base.Operation] = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_name", models.CharField(max_length=255, verbose_name="sender name")),
                ("sender_email", models.EmailField(max_length=254, verbose_name="sender email")),
                ("sender_phone", models.CharField(blank=True, max_length=50, verbose_name="sender phone")),
                ("subject", models.CharField(blank=True, max_length=500, verbose_name="subject")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("booking", "Booking"),
                            ("support", "Support"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                        verbose_name="topic",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("processed", "Processed"), ("spam", "Spam")],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact_form", "Contact Form"),
                            ("email_import", "Email Import"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="contact_form",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp"), ("telegram", "Telegram")],
                        db_index=True,
                        default="email",
                        max_length=20,
                        verbose_name="channel",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="read")),
                ("is_archived", models.BooleanField(db_index=True, default=False, verbose_name="archived")),
                (
                    "dsgvo_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Client confirmed data processing agreement",
                        verbose_name="DSGVO consent",
                    ),
                ),
                (
                    "consent_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Client agreed to receive marketing communications",
                        verbose_name="marketing consent",
                    ),
                ),
                ("lang", models.CharField(blank=True, default="de", max_length=10, verbose_name="language")),
                ("admin_notes", models.TextField(blank=True, verbose_name="admin notes")),
                (
                    "thread_key",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True, verbose_name="thread key"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(verbose_name="body")),
                ("sent_at", models.DateTimeField(auto_now_add=True, verbose_name="sent at")),
                ("is_inbound", models.BooleanField(default=False, verbose_name="inbound")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="conversations.message",
                        verbose_name="message",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reply",
                "verbose_name_plural": "Replies",
                "ordering": ["sent_at"],
            },
        ),
    ]
