# Generated by Django 5.2.12 on 2026-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_message_read_archive_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="admin notes"),
        ),
        migrations.AddField(
            model_name="message",
            name="consent_marketing",
            field=models.BooleanField(
                default=False,
                help_text="Client agreed to receive marketing communications",
                verbose_name="marketing consent",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="dsgvo_consent",
            field=models.BooleanField(
                default=False, help_text="Client confirmed data processing agreement", verbose_name="DSGVO consent"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="lang",
            field=models.CharField(blank=True, default="de", max_length=10, verbose_name="language"),
        ),
    ]
