# Generated by Django 5.2.13 on 2026-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_campaign"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="campaignrecipient",
            new_name="conversatio_campaig_ab0cbe_idx",
            old_name="conversatio_campaig_idx",
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_marketing",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, marketing consent will be ignored (use for critical updates).",
                verbose_name="is marketing",
            ),
        ),
    ]
