"""Scaffold-owned booking settings model for resource-slot booking.

This file is intended to be generated by the booking scaffold. Projects can
extend or replace this model if they need a different administrative settings
surface while keeping the runtime adapter expectations intact.
"""

from datetime import time

from codex_django.booking.mixins import AbstractBookingSettings
from django.db import models
from django.utils.translation import gettext_lazy as _


class BookingSettings(AbstractBookingSettings):
    STRATEGY_FILL_FIRST = "fill_first"
    STRATEGY_EVEN_LOAD = "even_load"
    STRATEGY_CHOICES = [
        (STRATEGY_FILL_FIRST, _("Fill first (by priority)")),
        (STRATEGY_EVEN_LOAD, _("Even load (balance bookings)")),
    ]

    load_strategy = models.CharField(
        _("master load strategy"),
        max_length=20,
        choices=STRATEGY_CHOICES,
        default=STRATEGY_FILL_FIRST,
        help_text=_(
            "fill_first: assign bookings to masters with lower booking_priority first. "
            "even_load: assign to the master with fewest bookings on the target date."
        ),
    )

    book_only_from_next_day = models.BooleanField(
        _("Public booking starts from next day"),
        default=False,
        help_text=_(
            "If enabled, clients can only book slots starting from tomorrow. Cabinet staff can still book today."
        ),
    )

    DEFAULT_DAY_HOURS = {
        "monday": (False, time(9, 0), time(18, 0)),
        "tuesday": (False, time(9, 0), time(18, 0)),
        "wednesday": (False, time(9, 0), time(18, 0)),
        "thursday": (False, time(9, 0), time(18, 0)),
        "friday": (False, time(9, 0), time(18, 0)),
        "saturday": (False, time(10, 0), time(14, 0)),
        "sunday": (True, None, None),
    }

    @classmethod
    def load(cls):
        obj, _created = cls.objects.get_or_create(pk=1)
        update_fields: list[str] = []
        for day, (is_closed, start, end) in cls.DEFAULT_DAY_HOURS.items():
            closed_field = f"{day}_is_closed"
            start_field = f"work_start_{day}"
            end_field = f"work_end_{day}"
            if getattr(obj, closed_field) != is_closed:
                setattr(obj, closed_field, is_closed)
                update_fields.append(closed_field)
            if getattr(obj, start_field) is None and start is not None:
                setattr(obj, start_field, start)
                update_fields.append(start_field)
            if getattr(obj, end_field) is None and end is not None:
                setattr(obj, end_field, end)
                update_fields.append(end_field)
        if update_fields:
            obj.save(update_fields=update_fields)
        return obj

    class Meta:
        verbose_name = "Resource-Slot Booking Settings"
        verbose_name_plural = "Resource-Slot Booking Settings"
