"""Scaffold-owned booking settings model for resource-slot booking.

This file is intended to be generated by the booking scaffold. Projects can
extend or replace this model if they need a different administrative settings
surface while keeping the runtime adapter expectations intact.
"""

from codex_django.booking.mixins import AbstractBookingSettings
from django.db import models
from django.utils.translation import gettext_lazy as _


class BookingSettings(AbstractBookingSettings):
    STRATEGY_FILL_FIRST = "fill_first"
    STRATEGY_EVEN_LOAD = "even_load"
    STRATEGY_CHOICES = [
        (STRATEGY_FILL_FIRST, _("Fill first (by priority)")),
        (STRATEGY_EVEN_LOAD, _("Even load (balance bookings)")),
    ]

    load_strategy = models.CharField(
        _("master load strategy"),
        max_length=20,
        choices=STRATEGY_CHOICES,
        default=STRATEGY_FILL_FIRST,
        help_text=_(
            "fill_first: assign bookings to masters with lower booking_priority first. "
            "even_load: assign to the master with fewest bookings on the target date."
        ),
    )

    book_only_from_next_day = models.BooleanField(
        _("Book only from next day"),
        default=False,
        help_text=_("If enabled, users can only book slots starting from tomorrow."),
    )
    sync_with_site_settings = models.BooleanField(
        _("Sync with Site Settings"),
        default=True,
        help_text=_("If enabled, work hours will be synchronized from global Site Settings."),
    )

    def save(self, *args, **kwargs):
        if self.sync_with_site_settings:
            try:
                from system.models import SiteSettings

                site = SiteSettings.load()
                self.work_start_weekdays = site.work_start_weekdays
                self.work_end_weekdays = site.work_end_weekdays
                self.work_start_saturday = site.work_start_saturday
                self.work_end_saturday = site.work_end_saturday
            except ImportError:
                pass
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

    class Meta:
        verbose_name = "Resource-Slot Booking Settings"
        verbose_name_plural = "Resource-Slot Booking Settings"
