# Generated by Django 5.2.13 on 2026-04-18 14:17

import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Key")),
                ("category", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="Category")),
                ("text", models.TextField(verbose_name="Text Content")),
                ("text_de", models.TextField(null=True, verbose_name="Text Content")),
                ("text_en", models.TextField(null=True, verbose_name="Text Content")),
                ("text_ru", models.TextField(null=True, verbose_name="Text Content")),
                ("text_uk", models.TextField(null=True, verbose_name="Text Content")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Email Content Block",
                "verbose_name_plural": "Email Content Blocks",
                "ordering": ["category", "key"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("address_street", models.CharField(blank=True, max_length=255, verbose_name="Street Address")),
                ("address_locality", models.CharField(blank=True, max_length=255, verbose_name="City/Locality")),
                ("address_postal_code", models.CharField(blank=True, max_length=10, verbose_name="Postal Code")),
                ("contact_person", models.CharField(blank=True, max_length=255, verbose_name="Contact Person")),
                ("working_hours", models.TextField(blank=True, verbose_name="Working Hours")),
                ("google_maps_link", models.URLField(blank=True, max_length=500, verbose_name="Google Maps Link")),
                ("latitude", models.CharField(blank=True, max_length=50, verbose_name="Latitude")),
                ("longitude", models.CharField(blank=True, max_length=50, verbose_name="Longitude")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram URL")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook URL")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram URL")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp URL")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube URL")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok URL")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter (X) URL")),
                ("pinterest_url", models.URLField(blank=True, verbose_name="Pinterest URL")),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Google Analytics ID"),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Google Tag Manager ID"),
                ),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50, verbose_name="Facebook Pixel ID")),
                ("tiktok_pixel_id", models.CharField(blank=True, max_length=50, verbose_name="TikTok Pixel ID")),
                ("app_mode_enabled", models.BooleanField(default=False, verbose_name="App Mode Enabled")),
                ("maintenance_mode", models.BooleanField(default=False, verbose_name="Maintenance Mode")),
                ("head_scripts", models.TextField(blank=True, verbose_name="Scripts in <head>")),
                ("body_scripts", models.TextField(blank=True, verbose_name="Scripts in <body>")),
                ("email_from", models.EmailField(blank=True, max_length=254, verbose_name="From Email")),
                ("email_sender_name", models.CharField(blank=True, max_length=255, verbose_name="Sender Name")),
                ("email_reply_to", models.EmailField(blank=True, max_length=254, verbose_name="Reply-To")),
                (
                    "company_name",
                    models.CharField(default="LILY Beauty Salon", max_length=255, verbose_name="Company Name"),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255, verbose_name="Owner Name")),
                ("tax_number", models.CharField(blank=True, max_length=100, verbose_name="Tax Number (Steuernummer)")),
                ("site_base_url", models.URLField(blank=True, verbose_name="Site Base URL")),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, default="/static/img/logo_lily.webp", max_length=500, verbose_name="Logo URL"
                    ),
                ),
                (
                    "telegram_bot_username",
                    models.CharField(
                        blank=True,
                        help_text="Username without @ (e.g., lily_beauty_bot)",
                        max_length=100,
                        verbose_name="Telegram Bot Username",
                    ),
                ),
                (
                    "working_hours_weekdays",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_weekdays_de",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_weekdays_en",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_weekdays_ru",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_weekdays_uk",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_saturday",
                    models.CharField(
                        blank=True, default="10:00 - 14:00", max_length=100, verbose_name="Saturday (Display)"
                    ),
                ),
                (
                    "working_hours_saturday_de",
                    models.CharField(
                        blank=True,
                        default="10:00 - 14:00",
                        max_length=100,
                        null=True,
                        verbose_name="Saturday (Display)",
                    ),
                ),
                (
                    "working_hours_saturday_en",
                    models.CharField(
                        blank=True,
                        default="10:00 - 14:00",
                        max_length=100,
                        null=True,
                        verbose_name="Saturday (Display)",
                    ),
                ),
                (
                    "working_hours_saturday_ru",
                    models.CharField(
                        blank=True,
                        default="10:00 - 14:00",
                        max_length=100,
                        null=True,
                        verbose_name="Saturday (Display)",
                    ),
                ),
                (
                    "working_hours_saturday_uk",
                    models.CharField(
                        blank=True,
                        default="10:00 - 14:00",
                        max_length=100,
                        null=True,
                        verbose_name="Saturday (Display)",
                    ),
                ),
                (
                    "working_hours_sunday",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, verbose_name="Sunday (Display)"
                    ),
                ),
                (
                    "working_hours_sunday_de",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
                    ),
                ),
                (
                    "working_hours_sunday_en",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
                    ),
                ),
                (
                    "working_hours_sunday_ru",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
                    ),
                ),
                (
                    "working_hours_sunday_uk",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
                    ),
                ),
                ("price_range", models.CharField(blank=True, default="$$", max_length=10, verbose_name="Price Range")),
                (
                    "url_path_contact_form",
                    models.CharField(default="/contacts/", max_length=255, verbose_name="Contact Form URL Path"),
                ),
                (
                    "url_path_confirm",
                    models.CharField(
                        default="/appointments/confirm/{token}/",
                        max_length=255,
                        verbose_name="Booking Confirm URL Path",
                    ),
                ),
                (
                    "url_path_cancel",
                    models.CharField(
                        default="/appointments/cancel/{token}/", max_length=255, verbose_name="Booking Cancel URL Path"
                    ),
                ),
                (
                    "url_path_reschedule",
                    models.CharField(
                        default="/cabinet/appointments/reschedule/{token}/",
                        max_length=255,
                        verbose_name="Booking Reschedule URL Path",
                    ),
                ),
                (
                    "hiring_active",
                    models.BooleanField(
                        default=True, help_text="Show 'We are hiring' block on Team page", verbose_name="Hiring Active"
                    ),
                ),
                (
                    "hiring_title",
                    models.CharField(
                        blank=True, default="Wir suchen Verstärkung!", max_length=255, verbose_name="Hiring Title"
                    ),
                ),
                (
                    "hiring_title_de",
                    models.CharField(
                        blank=True,
                        default="Wir suchen Verstärkung!",
                        max_length=255,
                        null=True,
                        verbose_name="Hiring Title",
                    ),
                ),
                (
                    "hiring_title_en",
                    models.CharField(
                        blank=True,
                        default="Wir suchen Verstärkung!",
                        max_length=255,
                        null=True,
                        verbose_name="Hiring Title",
                    ),
                ),
                (
                    "hiring_title_ru",
                    models.CharField(
                        blank=True,
                        default="Wir suchen Verstärkung!",
                        max_length=255,
                        null=True,
                        verbose_name="Hiring Title",
                    ),
                ),
                (
                    "hiring_title_uk",
                    models.CharField(
                        blank=True,
                        default="Wir suchen Verstärkung!",
                        max_length=255,
                        null=True,
                        verbose_name="Hiring Title",
                    ),
                ),
                (
                    "hiring_text",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        verbose_name="Hiring Text",
                    ),
                ),
                (
                    "hiring_text_de",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        null=True,
                        verbose_name="Hiring Text",
                    ),
                ),
                (
                    "hiring_text_en",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        null=True,
                        verbose_name="Hiring Text",
                    ),
                ),
                (
                    "hiring_text_ru",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        null=True,
                        verbose_name="Hiring Text",
                    ),
                ),
                (
                    "hiring_text_uk",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        null=True,
                        verbose_name="Hiring Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StaticPageSeo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_title_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_uk", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_description_de", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_en", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_ru", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_uk", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Главная страница"),
                            ("contacts", "Контакты"),
                            ("team", "Команда"),
                            ("services_index", "Список услуг"),
                            ("impressum", "Impressum"),
                            ("datenschutz", "Datenschutz"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="ID Страницы",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO статичной страницы",
                "verbose_name_plural": "SEO статичных страниц",
            },
        ),
        migrations.CreateModel(
            name="StaticTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the content piece.",
                        max_length=255,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                ("content", models.TextField(blank=True, help_text="The translated content.", verbose_name="Content")),
                (
                    "content_de",
                    models.TextField(
                        blank=True, help_text="The translated content.", null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True, help_text="The translated content.", null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        blank=True, help_text="The translated content.", null=True, verbose_name="Content"
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        blank=True, help_text="The translated content.", null=True, verbose_name="Content"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статический перевод",
                "verbose_name_plural": "Статические переводы",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=255, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=255, verbose_name="last name")),
                ("patronymic", models.CharField(blank=True, max_length=255, verbose_name="patronymic")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="email")),
                ("consent_marketing", models.BooleanField(default=False, verbose_name="marketing consent")),
                ("consent_analytics", models.BooleanField(default=False, verbose_name="analytics consent")),
                ("consent_date", models.DateTimeField(blank=True, null=True, verbose_name="consent date")),
                (
                    "is_ghost",
                    models.BooleanField(
                        default=True,
                        help_text="True if the client was created by staff and hasn't registered/linked an account yet.",
                        verbose_name="is ghost",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("guest", "Guest"), ("active", "Active"), ("blocked", "Blocked")],
                        db_index=True,
                        default="guest",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name="access token"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="internal note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("patronymic", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How the profile was created: booking / form / manual / allauth",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instagram", models.CharField(blank=True, max_length=100, verbose_name="Instagram")),
                ("telegram", models.CharField(blank=True, max_length=100, verbose_name="Telegram")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Birth Date")),
                ("show_avatar", models.BooleanField(default=True, verbose_name="Show Avatar")),
                ("show_birth_date", models.BooleanField(default=True, verbose_name="Show Birth Date")),
                ("show_visit_history", models.BooleanField(default=True, verbose_name="Show Visit History")),
                ("use_recommendations", models.BooleanField(default=True, verbose_name="Use Recommendations")),
                ("notify_service", models.BooleanField(default=True, verbose_name="Service Notifications")),
                ("notify_reminders", models.BooleanField(default=True, verbose_name="Appointment Reminders")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="level",
                    ),
                ),
                (
                    "best_level",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="best level",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="progress percent",
                    ),
                ),
                (
                    "effective_spend_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="effective spend score"
                    ),
                ),
                (
                    "behavior_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name="behavior multiplier"),
                ),
                ("source_hash", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="source hash")),
                ("calculated_at", models.DateTimeField(blank=True, null=True, verbose_name="calculated at")),
                ("stats", models.JSONField(blank=True, default=dict, verbose_name="stats")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to="system.userprofile",
                        verbose_name="user profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty Profile",
                "verbose_name_plural": "Loyalty Profiles",
                "ordering": ["-level", "-effective_spend_score"],
            },
        ),
    ]
