# Generated by Django 5.2.12 on 2026-04-05 19:37

import datetime

import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("address_street", models.CharField(blank=True, max_length=255, verbose_name="Street Address")),
                ("address_locality", models.CharField(blank=True, max_length=255, verbose_name="City/Locality")),
                ("address_postal_code", models.CharField(blank=True, max_length=10, verbose_name="Postal Code")),
                ("contact_person", models.CharField(blank=True, max_length=255, verbose_name="Contact Person")),
                ("working_hours", models.TextField(blank=True, verbose_name="Working Hours")),
                ("google_maps_link", models.URLField(blank=True, max_length=500, verbose_name="Google Maps Link")),
                ("latitude", models.CharField(blank=True, max_length=50, verbose_name="Latitude")),
                ("longitude", models.CharField(blank=True, max_length=50, verbose_name="Longitude")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram URL")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook URL")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram URL")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp URL")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube URL")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok URL")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter (X) URL")),
                ("pinterest_url", models.URLField(blank=True, verbose_name="Pinterest URL")),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Google Analytics ID"),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Google Tag Manager ID"),
                ),
                ("facebook_pixel_id", models.CharField(blank=True, max_length=50, verbose_name="Facebook Pixel ID")),
                ("tiktok_pixel_id", models.CharField(blank=True, max_length=50, verbose_name="TikTok Pixel ID")),
                ("app_mode_enabled", models.BooleanField(default=False, verbose_name="App Mode Enabled")),
                ("maintenance_mode", models.BooleanField(default=False, verbose_name="Maintenance Mode")),
                ("head_scripts", models.TextField(blank=True, verbose_name="Scripts in <head>")),
                ("body_scripts", models.TextField(blank=True, verbose_name="Scripts in <body>")),
                ("smtp_host", models.CharField(blank=True, max_length=255, verbose_name="SMTP Host")),
                ("smtp_port", models.IntegerField(default=465, verbose_name="SMTP Port")),
                ("smtp_user", models.CharField(blank=True, max_length=255, verbose_name="SMTP User")),
                ("smtp_password", models.CharField(blank=True, max_length=255, verbose_name="SMTP Password")),
                ("smtp_from_email", models.EmailField(blank=True, max_length=254, verbose_name="SMTP From Email")),
                ("smtp_use_tls", models.BooleanField(default=True, verbose_name="Use TLS")),
                ("smtp_use_ssl", models.BooleanField(default=False, verbose_name="Use SSL")),
                ("sendgrid_api_key", models.CharField(blank=True, max_length=255, verbose_name="SendGrid API Key")),
                (
                    "company_name",
                    models.CharField(default="LILY Beauty Salon", max_length=255, verbose_name="Company Name"),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255, verbose_name="Owner Name")),
                ("tax_number", models.CharField(blank=True, max_length=100, verbose_name="Tax Number (Steuernummer)")),
                ("site_base_url", models.URLField(blank=True, verbose_name="Site Base URL")),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, default="/static/img/logo_lily.webp", max_length=500, verbose_name="Logo URL"
                    ),
                ),
                (
                    "telegram_bot_username",
                    models.CharField(
                        blank=True,
                        help_text="Username without @ (e.g., lily_beauty_bot)",
                        max_length=100,
                        verbose_name="Telegram Bot Username",
                    ),
                ),
                (
                    "working_hours_weekdays",
                    models.CharField(
                        blank=True, default="09:00 - 18:00", max_length=100, verbose_name="Mo-Fr (Display)"
                    ),
                ),
                (
                    "working_hours_saturday",
                    models.CharField(
                        blank=True, default="10:00 - 14:00", max_length=100, verbose_name="Saturday (Display)"
                    ),
                ),
                (
                    "working_hours_sunday",
                    models.CharField(
                        blank=True, default="Geschlossen", max_length=100, verbose_name="Sunday (Display)"
                    ),
                ),
                ("work_start_weekdays", models.TimeField(default=datetime.time(9, 0), verbose_name="Mo-Fr Start")),
                ("work_end_weekdays", models.TimeField(default=datetime.time(18, 0), verbose_name="Mo-Fr End")),
                ("work_start_saturday", models.TimeField(default=datetime.time(10, 0), verbose_name="Saturday Start")),
                ("work_end_saturday", models.TimeField(default=datetime.time(14, 0), verbose_name="Saturday End")),
                ("price_range", models.CharField(blank=True, default="$$", max_length=10, verbose_name="Price Range")),
                (
                    "url_path_contact_form",
                    models.CharField(default="/contacts/", max_length=255, verbose_name="Contact Form URL Path"),
                ),
                (
                    "url_path_confirm",
                    models.CharField(
                        default="/appointments/confirm/{token}/",
                        max_length=255,
                        verbose_name="Booking Confirm URL Path",
                    ),
                ),
                (
                    "url_path_cancel",
                    models.CharField(
                        default="/appointments/cancel/{token}/", max_length=255, verbose_name="Booking Cancel URL Path"
                    ),
                ),
                (
                    "url_path_reschedule",
                    models.CharField(
                        default="/cabinet/appointments/reschedule/{token}/",
                        max_length=255,
                        verbose_name="Booking Reschedule URL Path",
                    ),
                ),
                (
                    "hiring_active",
                    models.BooleanField(
                        default=True, help_text="Show 'We are hiring' block on Team page", verbose_name="Hiring Active"
                    ),
                ),
                (
                    "hiring_title",
                    models.CharField(
                        blank=True, default="Wir suchen Verstärkung!", max_length=255, verbose_name="Hiring Title"
                    ),
                ),
                (
                    "hiring_text",
                    models.TextField(
                        blank=True,
                        default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                        verbose_name="Hiring Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StaticPageSeo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Главная страница"),
                            ("contacts", "Контакты"),
                            ("team", "Команда"),
                            ("services_index", "Список услуг"),
                            ("impressum", "Impressum"),
                            ("datenschutz", "Datenschutz"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="ID Страницы",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO статичной страницы",
                "verbose_name_plural": "SEO статичных страниц",
            },
        ),
        migrations.CreateModel(
            name="StaticTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the content piece.",
                        max_length=255,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                ("content", models.TextField(blank=True, help_text="The translated content.", verbose_name="Content")),
            ],
            options={
                "verbose_name": "Статический перевод",
                "verbose_name_plural": "Статические переводы",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("patronymic", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How the profile was created: booking / form / manual / allauth",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "ordering": ["-created_at"],
            },
        ),
    ]
