# Generated by Django 5.2.12 on 2026-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Key")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General / Shared"),
                            ("booking", "Booking System"),
                            ("contacts", "Contact Form / CRM"),
                            ("marketing", "Marketing / Newsletters"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text Content")),
                ("text_en", models.TextField(null=True, verbose_name="Text Content")),
                ("text_ru", models.TextField(null=True, verbose_name="Text Content")),
                ("text_de", models.TextField(null=True, verbose_name="Text Content")),
                ("text_uk", models.TextField(null=True, verbose_name="Text Content")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Email Content Block",
                "verbose_name_plural": "Email Content Blocks",
                "ordering": ["category", "key"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_text_de",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_text_en",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_text_ru",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_text_uk",
            field=models.TextField(
                blank=True,
                default="Bist du talentiert und liebst deinen Job? Werde Teil unseres Teams!",
                null=True,
                verbose_name="Hiring Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_title_de",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_title_en",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_title_ru",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hiring_title_uk",
            field=models.CharField(
                blank=True, default="Wir suchen Verstärkung!", max_length=255, null=True, verbose_name="Hiring Title"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_saturday_de",
            field=models.CharField(
                blank=True, default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_saturday_en",
            field=models.CharField(
                blank=True, default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_saturday_ru",
            field=models.CharField(
                blank=True, default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_saturday_uk",
            field=models.CharField(
                blank=True, default="10:00 - 14:00", max_length=100, null=True, verbose_name="Saturday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_sunday_de",
            field=models.CharField(
                blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_sunday_en",
            field=models.CharField(
                blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_sunday_ru",
            field=models.CharField(
                blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_sunday_uk",
            field=models.CharField(
                blank=True, default="Geschlossen", max_length=100, null=True, verbose_name="Sunday (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_weekdays_de",
            field=models.CharField(
                blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_weekdays_en",
            field=models.CharField(
                blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_weekdays_ru",
            field=models.CharField(
                blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours_weekdays_uk",
            field=models.CharField(
                blank=True, default="09:00 - 18:00", max_length=100, null=True, verbose_name="Mo-Fr (Display)"
            ),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_description_de",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_description_en",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_title_de",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_title_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_title_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="staticpageseo",
            name="seo_title_uk",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title"),
        ),
        migrations.AddField(
            model_name="statictranslation",
            name="content_de",
            field=models.TextField(blank=True, help_text="The translated content.", null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="statictranslation",
            name="content_en",
            field=models.TextField(blank=True, help_text="The translated content.", null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="statictranslation",
            name="content_ru",
            field=models.TextField(blank=True, help_text="The translated content.", null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="statictranslation",
            name="content_uk",
            field=models.TextField(blank=True, help_text="The translated content.", null=True, verbose_name="Content"),
        ),
    ]
