# Generated by Django 5.2.12 on 2026-04-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_emailcontent_sitesettings_hiring_text_de_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=255, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=255, verbose_name="last name")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="email")),
                (
                    "is_ghost",
                    models.BooleanField(
                        default=True,
                        help_text="True if the client was created by staff and hasn't registered/linked an account yet.",
                        verbose_name="is ghost",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name="access token"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="internal note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
