# Generated by Django 5.2.12 on 2026-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="consent_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="consent date"),
        ),
        migrations.AddField(
            model_name="client",
            name="consent_marketing",
            field=models.BooleanField(default=False, verbose_name="marketing consent"),
        ),
        migrations.AddField(
            model_name="client",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, verbose_name="instagram"),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("guest", "Guest"), ("active", "Active"), ("blocked", "Blocked")],
                db_index=True,
                default="guest",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, verbose_name="telegram"),
        ),
    ]
