# Generated by Django 5.2.12 on 2026-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_client_extend_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="consent_analytics",
            field=models.BooleanField(default=False, verbose_name="analytics consent"),
        ),
        migrations.AddField(
            model_name="client",
            name="show_avatar",
            field=models.BooleanField(default=True, verbose_name="show profile photo"),
        ),
        migrations.AddField(
            model_name="client",
            name="show_birth_date",
            field=models.BooleanField(default=False, verbose_name="show birth date"),
        ),
        migrations.AddField(
            model_name="client",
            name="show_visit_history",
            field=models.BooleanField(default=True, verbose_name="show visit history"),
        ),
        migrations.AddField(
            model_name="client",
            name="use_recommendations",
            field=models.BooleanField(default=True, verbose_name="personal recommendations"),
        ),
    ]
