# Generated by Django 5.2.12 on 2026-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_client_consent_analytics_client_show_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="client",
            name="patronymic",
            field=models.CharField(blank=True, max_length=255, verbose_name="patronymic / middle name"),
        ),
    ]
