# Generated by Django 5.2.12 on 2026-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_client_birth_date_client_patronymic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"], "verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.RemoveField(
            model_name="client",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="client",
            name="show_avatar",
        ),
        migrations.RemoveField(
            model_name="client",
            name="show_birth_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="show_visit_history",
        ),
        migrations.RemoveField(
            model_name="client",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="client",
            name="use_recommendations",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_avatar",
            field=models.BooleanField(default=True, verbose_name="Show Avatar"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_birth_date",
            field=models.BooleanField(default=True, verbose_name="Show Birth Date"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_visit_history",
            field=models.BooleanField(default=True, verbose_name="Show Visit History"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram",
            field=models.CharField(blank=True, max_length=100, verbose_name="Telegram"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="use_recommendations",
            field=models.BooleanField(default=True, verbose_name="Use Recommendations"),
        ),
        migrations.AlterField(
            model_name="client",
            name="patronymic",
            field=models.CharField(blank=True, max_length=255, verbose_name="patronymic"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
    ]
