# Generated by Django 5.2.12 on 2026-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_client_options_remove_client_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notify_reminders",
            field=models.BooleanField(default=True, verbose_name="Appointment Reminders"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_service",
            field=models.BooleanField(default=True, verbose_name="Service Notifications"),
        ),
    ]
