# Generated by Django 5.2.13 on 2026-04-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_title_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_uk", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_description_de", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_en", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_ru", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_uk", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("name_de", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_uk", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "bento_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hair", "Friseur & Styling"),
                            ("nails", "Nagelservice"),
                            ("face", "Kosmetologie"),
                            ("eyes", "Brows & Lashes"),
                            ("body", "Massage & Relax"),
                            ("hair_removal", "Depilation"),
                        ],
                        max_length=20,
                        verbose_name="bento group",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="categories/", verbose_name="image")),
                ("icon", models.FileField(blank=True, null=True, upload_to="categories/icons/", verbose_name="icon")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("description_de", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_ru", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_uk", models.TextField(blank=True, null=True, verbose_name="description")),
                ("content", models.TextField(blank=True, verbose_name="SEO content")),
                ("content_de", models.TextField(blank=True, null=True, verbose_name="SEO content")),
                ("content_en", models.TextField(blank=True, null=True, verbose_name="SEO content")),
                ("content_ru", models.TextField(blank=True, null=True, verbose_name="SEO content")),
                ("content_uk", models.TextField(blank=True, null=True, verbose_name="SEO content")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this category will be hidden from the website entirely.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge. Used for categories that will be available later.",
                        verbose_name="coming soon",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCombo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("name_de", models.CharField(max_length=200, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=200, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=200, null=True, verbose_name="name")),
                ("name_uk", models.CharField(max_length=200, null=True, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("description_de", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_ru", models.TextField(blank=True, null=True, verbose_name="description")),
                ("description_uk", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent discount (e.g. -10%)"),
                            ("fixed", "Fixed discount (e.g. -5€)"),
                            ("fixed_price", "Fixed combo price"),
                        ],
                        default="percent",
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent (10 = 10%) or fixed amount in euros.",
                        max_digits=10,
                        verbose_name="discount value",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="valid from")),
                ("valid_until", models.DateField(blank=True, null=True, verbose_name="valid until")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "Service Combo",
                "verbose_name_plural": "Service Combos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO Title")),
                ("seo_title_de", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_ru", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_title_uk", models.CharField(blank=True, max_length=255, null=True, verbose_name="SEO Title")),
                ("seo_description", models.TextField(blank=True, verbose_name="SEO Description")),
                ("seo_description_de", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_en", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_ru", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_description_uk", models.TextField(blank=True, null=True, verbose_name="SEO Description")),
                ("seo_image", models.ImageField(blank=True, null=True, upload_to="seo/", verbose_name="OG Image")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Service duration in minutes.", verbose_name="Duration (min)"
                    ),
                ),
                (
                    "min_gap_after_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cleanup/preparation time after this service.",
                        verbose_name="Gap After Service (min)",
                    ),
                ),
                (
                    "parallel_ok",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this service can be performed alongside another.",
                        verbose_name="Allow Parallel",
                    ),
                ),
                (
                    "parallel_group",
                    models.CharField(
                        blank=True,
                        help_text="Services in the same group can run simultaneously.",
                        max_length=50,
                        verbose_name="Parallel Group",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("name_de", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_uk", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="price (€)")),
                ("price_info", models.CharField(blank=True, max_length=100, verbose_name="price display text")),
                (
                    "price_info_de",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="price display text"),
                ),
                (
                    "price_info_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="price display text"),
                ),
                (
                    "price_info_ru",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="price display text"),
                ),
                (
                    "price_info_uk",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="price display text"),
                ),
                ("duration_info", models.CharField(blank=True, max_length=100, verbose_name="duration display text")),
                (
                    "duration_info_de",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="duration display text"),
                ),
                (
                    "duration_info_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="duration display text"),
                ),
                (
                    "duration_info_ru",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="duration display text"),
                ),
                (
                    "duration_info_uk",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="duration display text"),
                ),
                ("description", models.TextField(blank=True, verbose_name="short description")),
                ("description_de", models.TextField(blank=True, null=True, verbose_name="short description")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="short description")),
                ("description_ru", models.TextField(blank=True, null=True, verbose_name="short description")),
                ("description_uk", models.TextField(blank=True, null=True, verbose_name="short description")),
                ("content", models.TextField(blank=True, verbose_name="full content")),
                ("content_de", models.TextField(blank=True, null=True, verbose_name="full content")),
                ("content_en", models.TextField(blank=True, null=True, verbose_name="full content")),
                ("content_ru", models.TextField(blank=True, null=True, verbose_name="full content")),
                ("content_uk", models.TextField(blank=True, null=True, verbose_name="full content")),
                ("image", models.ImageField(blank=True, null=True, upload_to="services/", verbose_name="image")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("is_hit", models.BooleanField(default=False, verbose_name="popular / hit")),
                ("is_addon", models.BooleanField(default=False, verbose_name="is add-on")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("excludes", models.ManyToManyField(blank=True, to="main.service", verbose_name="excludes services")),
                (
                    "masters",
                    models.ManyToManyField(
                        blank=True, related_name="services", to="booking.master", verbose_name="masters"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="main.servicecategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceComboItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If false, this service is optional within the combo.",
                        verbose_name="required",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="order")),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main.servicecombo",
                        verbose_name="combo",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_items",
                        to="main.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Item",
                "verbose_name_plural": "Combo Items",
                "ordering": ["order"],
                "unique_together": {("combo", "service")},
            },
        ),
        migrations.CreateModel(
            name="ServiceConflictRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("replaces", "Replaces (adds source, removes target from cart)"),
                            ("excludes", "Excludes (cannot be in cart together)"),
                        ],
                        default="replaces",
                        max_length=20,
                        verbose_name="rule type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="admin note")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_rules_from",
                        to="main.service",
                        verbose_name="source service",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_rules_to",
                        to="main.service",
                        verbose_name="target service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Conflict Rule",
                "verbose_name_plural": "Service Conflict Rules",
                "unique_together": {("source", "target", "rule_type")},
            },
        ),
    ]
