# Generated by Django 5.2.13 on 2026-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, this category will be hidden from the website entirely.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="is_planned",
            field=models.BooleanField(
                default=False,
                help_text="If checked, shows 'Coming Soon' badge. Used for categories that will be available later.",
                verbose_name="coming soon",
            ),
        ),
    ]
