# Generated by Django 5.2.11 on 2026-02-10 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0002_load_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary contact method",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Email for notifications and account activation",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Client's name (collected during booking)",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Used in SMS/Email links for appointment management",
                        max_length=64,
                        unique=True,
                        verbose_name="Access Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("guest", "Guest (Temporary)"),
                            ("active", "Active (Registered)"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="guest",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "consent_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Client agreed to receive promotional materials",
                        verbose_name="Marketing Consent",
                    ),
                ),
                ("consent_date", models.DateTimeField(blank=True, null=True, verbose_name="Consent Given Date")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin-only notes about the client", verbose_name="Internal Notes"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked when client activates account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Django User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, help_text="Meta description for search engines.", verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_description_de",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Master's full name (e.g. 'Maria Ivanova')", max_length=255, verbose_name="Full Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL part (e.g. 'maria-ivanova')", unique=True, verbose_name="Slug"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Professional portrait (recommended: 800x1000px)",
                        null=True,
                        upload_to="masters/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Lead Nail Artist'",
                        max_length=255,
                        verbose_name="Professional Title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Lead Nail Artist'",
                        max_length=255,
                        null=True,
                        verbose_name="Professional Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Lead Nail Artist'",
                        max_length=255,
                        null=True,
                        verbose_name="Professional Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Lead Nail Artist'",
                        max_length=255,
                        null=True,
                        verbose_name="Professional Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Top Colorist', 'Lead Nail Artist'",
                        max_length=255,
                        null=True,
                        verbose_name="Professional Title",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Full biography and work philosophy (HTML allowed)",
                        verbose_name="Biography",
                    ),
                ),
                (
                    "bio_de",
                    models.TextField(
                        blank=True,
                        help_text="Full biography and work philosophy (HTML allowed)",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "bio_ru",
                    models.TextField(
                        blank=True,
                        help_text="Full biography and work philosophy (HTML allowed)",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "bio_uk",
                    models.TextField(
                        blank=True,
                        help_text="Full biography and work philosophy (HTML allowed)",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "bio_en",
                    models.TextField(
                        blank=True,
                        help_text="Full biography and work philosophy (HTML allowed)",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief intro for Team page (1-2 sentences)",
                        max_length=500,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_de",
                    models.CharField(
                        blank=True,
                        help_text="Brief intro for Team page (1-2 sentences)",
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_ru",
                    models.CharField(
                        blank=True,
                        help_text="Brief intro for Team page (1-2 sentences)",
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_uk",
                    models.CharField(
                        blank=True,
                        help_text="Brief intro for Team page (1-2 sentences)",
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        help_text="Brief intro for Team page (1-2 sentences)",
                        max_length=500,
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0, verbose_name="Years of Experience")),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="Username only (e.g. 'maria.beauty')",
                        max_length=100,
                        verbose_name="Instagram Handle",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Direct Phone")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active (Working)"),
                            ("vacation", "On Vacation"),
                            ("fired", "Fired/Left"),
                            ("training", "In Training"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="We never delete masters, only change status",
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False, help_text="Display as salon owner with special styling", verbose_name="Is Owner"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="Featured Master")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first", verbose_name="Display Order"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="For bot authentication and notifications",
                        null=True,
                        unique=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                ("telegram_username", models.CharField(blank=True, max_length=100, verbose_name="Telegram Username")),
                (
                    "bot_access_code",
                    models.CharField(
                        editable=False,
                        help_text="One-time code for master registration in bot",
                        max_length=8,
                        unique=True,
                        verbose_name="Bot Access Code",
                    ),
                ),
                ("qr_token", models.CharField(editable=False, max_length=32, unique=True, verbose_name="QR Token")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="High-level categories for filtering",
                        related_name="masters",
                        to="main.category",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "service_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific service groups this master can perform",
                        related_name="masters",
                        to="main.servicegroup",
                        verbose_name="Service Groups",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked when master needs personal cabinet access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="master_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Django User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master",
                "verbose_name_plural": "Masters",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "datetime_start",
                    models.DateTimeField(
                        db_index=True, help_text="Appointment start time", verbose_name="Start Date & Time"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Service duration (auto-filled from Service model)", verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at booking time (snapshot)",
                        max_digits=10,
                        verbose_name="Price (€)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At")),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client", "Cancelled by Client"),
                            ("master", "Cancelled by Master"),
                            ("reschedule", "Rescheduled"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Cancellation Reason",
                    ),
                ),
                (
                    "cancel_note",
                    models.TextField(
                        blank=True, help_text="Additional details about cancellation", verbose_name="Cancellation Note"
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special requests from client (e.g. allergies, preferences)",
                        verbose_name="Client Notes",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not visible to client)", verbose_name="Admin Notes"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="SMS/Email reminder was sent", verbose_name="Reminder Sent"
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Reminder Sent At")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="main.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="booking.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="booking.master",
                        verbose_name="Master",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-datetime_start"],
            },
        ),
        migrations.CreateModel(
            name="MasterCertificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Advanced Nail Art Course'", max_length=255, verbose_name="Certificate Title"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        help_text="e.g. 'Advanced Nail Art Course'",
                        max_length=255,
                        null=True,
                        verbose_name="Certificate Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="e.g. 'Advanced Nail Art Course'",
                        max_length=255,
                        null=True,
                        verbose_name="Certificate Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="e.g. 'Advanced Nail Art Course'",
                        max_length=255,
                        null=True,
                        verbose_name="Certificate Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="e.g. 'Advanced Nail Art Course'",
                        max_length=255,
                        null=True,
                        verbose_name="Certificate Title",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'German Beauty Academy'",
                        max_length=255,
                        verbose_name="Issuing Organization",
                    ),
                ),
                (
                    "issuer_de",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'German Beauty Academy'",
                        max_length=255,
                        null=True,
                        verbose_name="Issuing Organization",
                    ),
                ),
                (
                    "issuer_ru",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'German Beauty Academy'",
                        max_length=255,
                        null=True,
                        verbose_name="Issuing Organization",
                    ),
                ),
                (
                    "issuer_uk",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'German Beauty Academy'",
                        max_length=255,
                        null=True,
                        verbose_name="Issuing Organization",
                    ),
                ),
                (
                    "issuer_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'German Beauty Academy'",
                        max_length=255,
                        null=True,
                        verbose_name="Issuing Organization",
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True, verbose_name="Issue Date")),
                (
                    "image",
                    models.ImageField(
                        help_text="Scan or photo of certificate (recommended: 1200x900px)",
                        upload_to="certificates/",
                        verbose_name="Certificate Image",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first", verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on master page", verbose_name="Active"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="booking.master",
                        verbose_name="Master",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Certificate",
                "verbose_name_plural": "Master Certificates",
                "ordering": ["master", "order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="MasterPortfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "image",
                    models.ImageField(
                        help_text="Example of master's work (recommended: 1200x1200px)",
                        upload_to="portfolio/",
                        verbose_name="Portfolio Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work (technique, products used, etc.)",
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work (technique, products used, etc.)",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work (technique, products used, etc.)",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work (technique, products used, etc.)",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work (technique, products used, etc.)",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first", verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on master page", verbose_name="Active"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Link to original Instagram post", verbose_name="Instagram Post URL"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="booking.master",
                        verbose_name="Master",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to service this example demonstrates",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_examples",
                        to="main.service",
                        verbose_name="Related Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["master", "order", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["phone", "status"], name="booking_cli_phone_bdef6d_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email", "status"], name="booking_cli_email_fcbe6e_idx"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), ("phone", ""), _negated=True), name="client_must_have_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["master", "datetime_start"], name="booking_app_master__f409ed_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["client", "datetime_start"], name="booking_app_client__a402ed_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status", "datetime_start"], name="booking_app_status_b4a9a1_idx"),
        ),
    ]
