# Generated by Django 5.2.11 on 2026-02-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="main.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked when client activates account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Django User Account",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="booking.client",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="High-level categories for filtering",
                related_name="masters",
                to="main.category",
                verbose_name="Categories",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked when master needs personal cabinet access",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Django User Account",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="booking.master",
                verbose_name="Master",
            ),
        ),
        migrations.AddField(
            model_name="mastercertificate",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="booking.master",
                verbose_name="Master",
            ),
        ),
        migrations.AddField(
            model_name="masterportfolio",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_items",
                to="booking.master",
                verbose_name="Master",
            ),
        ),
        migrations.AddField(
            model_name="masterportfolio",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to service this example demonstrates",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_examples",
                to="main.service",
                verbose_name="Related Service",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["phone", "status"], name="booking_cli_phone_bdef6d_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email", "status"], name="booking_cli_email_fcbe6e_idx"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), ("phone", ""), _negated=True), name="client_must_have_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["master", "datetime_start"], name="booking_app_master__f409ed_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["client", "datetime_start"], name="booking_app_client__a402ed_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status", "datetime_start"], name="booking_app_status_b4a9a1_idx"),
        ),
    ]
