# Generated by Django 5.2.11 on 2026-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_load_initial_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="First Name"),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Last Name"),
        ),
    ]
