# Generated by Django 5.2.11 on 2026-02-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_client_name_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="instagram",
            field=models.CharField(blank=True, help_text="Username or link", max_length=100, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="client",
            name="telegram",
            field=models.CharField(blank=True, help_text="Username or link", max_length=100, verbose_name="Telegram"),
        ),
    ]
