# Generated by Django 5.2.11 on 2026-02-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_appointment_active_promo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterDayOff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Reason")),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="days_off", to="booking.master"
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Day Off",
                "verbose_name_plural": "Master Days Off",
                "ordering": ["date"],
                "unique_together": {("master", "date")},
            },
        ),
    ]
