# Generated by Django 5.2.11 on 2026-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_client_instagram_client_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="name_de",
            field=models.CharField(
                help_text="Master's full name (e.g. 'Maria Ivanova')",
                max_length=255,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="name_en",
            field=models.CharField(
                help_text="Master's full name (e.g. 'Maria Ivanova')",
                max_length=255,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="name_ru",
            field=models.CharField(
                help_text="Master's full name (e.g. 'Maria Ivanova')",
                max_length=255,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="name_uk",
            field=models.CharField(
                help_text="Master's full name (e.g. 'Maria Ivanova')",
                max_length=255,
                null=True,
                verbose_name="Full Name",
            ),
        ),
    ]
