# Generated by Django 5.2.11 on 2026-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_master_name_de_master_name_en_master_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("telegram", "Telegram Bot"),
                    ("phone", "Phone"),
                    ("admin", "Admin Panel"),
                ],
                default="website",
                help_text="Where this appointment was created",
                max_length=20,
                verbose_name="Booking Source",
            ),
        ),
    ]
