# Generated by Django 5.2.11 on 2026-03-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_appointment_finalize_token_appointment_price_actual_and_more"),
        ("main", "0005_service_min_gap_after_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "default_step_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Grid step in minutes for slot generation (e.g. 30 = slots at :00 and :30).",
                        verbose_name="Slot Step (min)",
                    ),
                ),
                (
                    "default_min_advance_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Global minimum: booking must be made at least N minutes before appointment. Can be overridden per master.",
                        verbose_name="Min Advance Booking (min)",
                    ),
                ),
                (
                    "default_max_advance_days",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Global maximum: booking cannot be made more than N days ahead. Can be overridden per master.",
                        verbose_name="Max Advance Booking (days)",
                    ),
                ),
                (
                    "default_buffer_between_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Global default: minutes a master needs between clients for preparation. 0 = no buffer. Can be overridden per master.",
                        verbose_name="Buffer Between Clients (min)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Settings",
                "verbose_name_plural": "Booking Settings",
            },
        ),
        migrations.AddField(
            model_name="master",
            name="break_end",
            field=models.TimeField(blank=True, help_text="Break end time.", null=True, verbose_name="Break End"),
        ),
        migrations.AddField(
            model_name="master",
            name="break_start",
            field=models.TimeField(
                blank=True,
                help_text="Break start time (lunch etc). Leave empty if no break.",
                null=True,
                verbose_name="Break Start",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="buffer_between_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minutes needed between clients for preparation. If empty, uses global default from Booking Settings.",
                null=True,
                verbose_name="Buffer Between Clients (min)",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="max_advance_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many days in advance a booking can be made. If empty, uses global default.",
                null=True,
                verbose_name="Max Advance Booking (days)",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="min_advance_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum minutes before appointment start a booking can be made. If empty, uses global default.",
                null=True,
                verbose_name="Min Advance Booking (min)",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="work_end",
            field=models.TimeField(
                blank=True,
                help_text="Individual work end time. If empty, uses salon schedule.",
                null=True,
                verbose_name="Work End",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="work_start",
            field=models.TimeField(
                blank=True,
                help_text="Individual work start time. If empty, uses salon schedule.",
                null=True,
                verbose_name="Work Start",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "booking_date",
                    models.DateField(
                        help_text="Primary date for the visit (all services for SINGLE_DAY mode).",
                        verbose_name="Booking Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "engine_mode",
                    models.CharField(
                        default="single_day",
                        help_text="BookingMode used when this group was created.",
                        max_length=30,
                        verbose_name="Engine Mode",
                    ),
                ),
                ("total_duration_minutes", models.PositiveIntegerField(default=0, verbose_name="Total Duration (min)")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_groups",
                        to="booking.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Group",
                "verbose_name_plural": "Appointment Groups",
                "ordering": ["-booking_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentGroupItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Position of this service in the booking chain (0-indexed).",
                        verbose_name="Order in Chain",
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_item",
                        to="booking.appointment",
                        verbose_name="Appointment",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="booking.appointmentgroup",
                        verbose_name="Group",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="main.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Group Item",
                "verbose_name_plural": "Appointment Group Items",
                "ordering": ["order"],
                "unique_together": {("group", "order")},
            },
        ),
    ]
