"""Scaffold-owned contract aliases for resource-slot booking.

This file is intended to be generated by the booking scaffold. It provides a
single import surface for projects that want to depend on booking contracts
without importing the runtime library layout directly.
"""

from codex_django.booking import (
    BookingActionResult,
    BookingBridge,
    BookingEngineGateway,
    BookingFeatureModels,
    BookingFormFieldState,
    BookingFormState,
    BookingModalActionState,
    BookingModalState,
    BookingProfileState,
    BookingProjectDataProvider,
    BookingSummaryItemState,
    BookingWorkflowService,
)

__all__ = [
    "BookingActionResult",
    "BookingBridge",
    "BookingEngineGateway",
    "BookingFeatureModels",
    "BookingFormFieldState",
    "BookingFormState",
    "BookingModalActionState",
    "BookingModalState",
    "BookingProfileState",
    "BookingProjectDataProvider",
    "BookingSummaryItemState",
    "BookingWorkflowService",
]
