# Generated by Django 5.2.11 on 2026-02-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this item will be completely hidden from the site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows 'Temporarily Unavailable' (e.g. no masters).",
                        verbose_name="Available for Booking",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge.",
                        verbose_name="Planned / Coming Soon",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_de",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Category name (e.g. 'Maniküre').",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        help_text="Category name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Category name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Category name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Category name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL part (e.g. 'manicure').",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "bento_group",
                    models.CharField(
                        choices=[
                            ("hair", "Friseur & Styling"),
                            ("nails", "Nagelservice"),
                            ("face", "Kosmetologie"),
                            ("eyes", "Brows & Lashes"),
                            ("body", "Massage & Relax"),
                            ("hair_removal", "Depilation"),
                        ],
                        default="hair",
                        help_text="Group for the main page grid (e.g. 'Nails' combines Manicure & Pedicure).",
                        max_length=20,
                        verbose_name="Bento Group",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Background image for Hero section and Bento card.",
                        upload_to="categories/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description displayed in the Hero section.",
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Short description displayed in the Hero section.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Short description displayed in the Hero section.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Short description displayed in the Hero section.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Short description displayed in the Hero section.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text displayed at the bottom of the category page.",
                        verbose_name="SEO Text / Content",
                    ),
                ),
                (
                    "content_de",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text displayed at the bottom of the category page.",
                        null=True,
                        verbose_name="SEO Text / Content",
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text displayed at the bottom of the category page.",
                        null=True,
                        verbose_name="SEO Text / Content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text displayed at the bottom of the category page.",
                        null=True,
                        verbose_name="SEO Text / Content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text displayed at the bottom of the category page.",
                        null=True,
                        verbose_name="SEO Text / Content",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="SVG icon for menu or footer (optional).",
                        null=True,
                        upload_to="categories/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sorting order (lower numbers come first).",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this item will be completely hidden from the site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows 'Temporarily Unavailable' (e.g. no masters).",
                        verbose_name="Available for Booking",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge.",
                        verbose_name="Planned / Coming Soon",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Browser tab title. Defaults to object title if empty.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_de",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Meta description for search engines.",
                        null=True,
                        verbose_name="SEO Description",
                    ),
                ),
                (
                    "seo_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Service name (e.g. 'Klassische Maniküre').",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        help_text="Service name (e.g. 'Klassische Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Service name (e.g. 'Klassische Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Service name (e.g. 'Klassische Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Service name (e.g. 'Klassische Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL part (e.g. 'classic-manicure').",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for sorting and calculation.",
                        max_digits=10,
                        verbose_name="Price (€)",
                    ),
                ),
                (
                    "price_info",
                    models.CharField(
                        blank=True,
                        help_text="Text to display (e.g. 'ab 30€'). If empty, uses Price field.",
                        max_length=100,
                        verbose_name="Price Display Text",
                    ),
                ),
                (
                    "price_info_de",
                    models.CharField(
                        blank=True,
                        help_text="Text to display (e.g. 'ab 30€'). If empty, uses Price field.",
                        max_length=100,
                        null=True,
                        verbose_name="Price Display Text",
                    ),
                ),
                (
                    "price_info_ru",
                    models.CharField(
                        blank=True,
                        help_text="Text to display (e.g. 'ab 30€'). If empty, uses Price field.",
                        max_length=100,
                        null=True,
                        verbose_name="Price Display Text",
                    ),
                ),
                (
                    "price_info_uk",
                    models.CharField(
                        blank=True,
                        help_text="Text to display (e.g. 'ab 30€'). If empty, uses Price field.",
                        max_length=100,
                        null=True,
                        verbose_name="Price Display Text",
                    ),
                ),
                (
                    "price_info_en",
                    models.CharField(
                        blank=True,
                        help_text="Text to display (e.g. 'ab 30€'). If empty, uses Price field.",
                        max_length=100,
                        null=True,
                        verbose_name="Price Display Text",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes.", verbose_name="Duration (min)"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in the list view.",
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_de",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in the list view.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in the list view.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in the list view.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in the list view.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description/article about the service (HTML/Markdown).",
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "content_de",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description/article about the service (HTML/Markdown).",
                        null=True,
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description/article about the service (HTML/Markdown).",
                        null=True,
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description/article about the service (HTML/Markdown).",
                        null=True,
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description/article about the service (HTML/Markdown).",
                        null=True,
                        verbose_name="Full Content",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the specific service.",
                        null=True,
                        upload_to="services/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_hit",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this service as popular.",
                        verbose_name="Hit / Popular",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Sorting order.", verbose_name="Order"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Main category (for filtering).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="main.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="High quality photo. Will be resized by CSS.",
                        upload_to="portfolio/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        verbose_name="Title / Description",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        null=True,
                        verbose_name="Title / Description",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        null=True,
                        verbose_name="Title / Description",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        null=True,
                        verbose_name="Title / Description",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        null=True,
                        verbose_name="Title / Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sorting order in the gallery.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_images",
                        to="main.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Image",
                "verbose_name_plural": "Portfolio Images",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this item will be completely hidden from the site.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows 'Temporarily Unavailable' (e.g. no masters).",
                        verbose_name="Available for Booking",
                    ),
                ),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, shows 'Coming Soon' badge.",
                        verbose_name="Planned / Coming Soon",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Group name (e.g. 'Maniküre').",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        help_text="Group name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Group name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Group name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Group name (e.g. 'Maniküre').",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sorting order within the category.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="main.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Group",
                "verbose_name_plural": "Service Groups",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional grouping within the category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="main.servicegroup",
                verbose_name="Group",
            ),
        ),
    ]
