# Generated by Django 5.2.11 on 2026-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_contactrequest_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_addon",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this service will be excluded from 'Price from' calculation on the home page.",
                verbose_name="Is Add-on",
            ),
        ),
    ]
