# Generated by Django 5.2.11 on 2026-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_contactrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
