# Generated by Django 5.2.11 on 2026-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_service_is_addon"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="min_gap_after_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum pause in minutes after this service before the next one in a chain booking (e.g. drying time, waiting). Default: 0.",
                verbose_name="Gap After Service (min)",
            ),
        ),
    ]
