# Generated by Django 5.2.11 on 2026-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_service_min_gap_after_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="excludes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select services that cannot be booked together with this one (e.g. Full Body excludes Back massage).",
                to="main.service",
                verbose_name="Excludes Services",
            ),
        ),
    ]
