# Generated by Django 5.2.11 on 2026-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_contactrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="duration_info",
            field=models.CharField(
                blank=True,
                help_text="Text to display (e.g. 'ca. 45-60 Min'). If empty, uses Duration field.",
                max_length=100,
                verbose_name="Duration Display Text",
            ),
        ),
    ]
